### ISSUE TITLE
The parameter is incorrect. Effect source #0 is associated with a different device. at System.Runtime.InteropService

### ISSUE THREAD

**Issue by myokeeh** [microsoft/Win2D#897] opened 2022-12-26 07:01 UTC
I'm running into an exception for Canvas_DrawAnimated that has an Exception message `The parameter is incorrect. Effect source #0 is associated with a different device. at System.Runtime.InteropService`. It's a little too vague for me to decipher. It's not readily reproducible so I only get this info via AppCenter or Partner Center crash reports. It is associated with an effect. What could it be?

**Comment by getrou** [comment] 2022-12-28 16:04
Hm, without any more information, I can only hazard a guess. Are you regenerating your resources on the new device when you get a DeviceLost?

**Comment by myokeeh** [comment] 2022-12-29 06:49
I'm unclear what device means in this context. The app runs on a single device if that helps.

I am also getting reports of an `UnhandledException`s with the following text: `"Invalid window handle. This API must be called from a thread with a CoreWindow or a window must have been set explicitly."`

FYI, the app is a UWP app. Using Win2D.uwp 1.27.0-preview1, but was also getting this with 1.26.0.

**Comment by getrou** [comment] 2022-12-29 16:14
The graphics device can sometimes be lost for various reasons (computer goes to sleep, a device is physically disconnected, driver failure, etc), and resources must be recreated. Win2D Controls have support for handling this; I recommend taking a look at this page: https://microsoft.github.io/Win2D/WinUI2/html/HandlingDeviceLost.htm

**Comment by myokeeh** [comment] 2022-12-30 04:50
@getrou, I see. I had a suspicion it might also be graphics card or driver related. 

I'm trying that syntax, but "`where`" doesn't seem to valid C#, but "`when`" is. However, `ee` does not have an `ErrorCode`

```
catch (Exception ee) when (sender.Device.IsDeviceLost(ee.ErrorCode))
            {
                //
            }
```

**Comment by myokeeh** [comment] 2022-12-30 04:56
FYI, I made some changes because I realized displaying a `MessageDialog` on a Win2D app that is running in Kiosk mode is probably not helping or causing the issue. I put it in because it was crashing and that was my quick way to debug the app while it was running in kiosk mode. The original crashing problem may have been a graphics card / driver issue as you're pointing out, so I'd like to catch that case.

**Comment by myokeeh** [comment] 2022-12-30 05:17
I just reviewed Reliability History on the kiosk PC and I see that there are windows hardware failures (graphics card driver) coinciding with the app crashes. The question is could I be doing anything in Win2D that is causing the graphics card driver to crash or are my app crashes caused by driver crashes?

**Comment by getrou** [comment] 2023-01-04 16:34
I think it is more likely that the graphics card driver failure is causing the app to crash due to not handling the Device Lost case than the app causing the driver to crash, although it is possible both are true. Diagnosing and working around driver bugs can be difficult.

Here are some possible next steps:
- Handle the Device Lost case and recreate your resources on the new device when it happens, so your app can handle the occasional graphics driver failure smoothly without crashing
- If you own the machines that the app is running on, try updating graphics drivers to see if they've released a fix for any driver bugs
- Put in some logging or telemetry to try and diagnose where your app might be causing the driver to crash to help you work around the driver bug.
- If you're only running your app on one machine, run your app on a machine with different hardware to isolate whether the issue is with the graphics driver or with your app

**Comment by myokeeh** [comment] 2023-01-05 06:05
@getrou I can't seem to get the code/syntax to build as presented on that help page to handle device lost per my comment above (https://github.com/microsoft/Win2D/issues/897#issuecomment-1367726547)

I put in telemetry to help me capture the specific line where it's failing, but of course now it's working flawlessly for hours.

Prior to putting the additional logging above, I put it back to its original state. The actual behavior of the app is not to crash. I think that was induced by the `MessageDialog` I added to display to show errors. The actual behavior is it blanks out the screen (just turns black) and nothing else is drawn. The app is still running. I did get some logs/telemetry of this when it got to this state and it logged about ~64,000 of `The parameter is incorrect. Effect source #0 is associated with a different device. at System.Runtime.InteropService`

Firmware and drivers are up-to-date on the kiosk PC.

**Comment by getrou** [comment] 2023-01-09 21:53
I see, I misunderstood your comment. That is a typo that needs to be fixed in the docs. It should read:
`catch (Exception ee) when (sender.Device.IsDeviceLost(ee.HResult))`

Give that a try and I think you'll be good to go to recreate your resources!

**Closed** 2023-01-19 19:20 UTC

**Comment by myokeeh** [comment] 2023-01-27 03:36
I've isolated this `The parameter is incorrect. Effect source #0 is associated with a different device. at System.Runtime.InteropService` error to the following line.

```
using (CanvasDrawingSession clds = cl1.CreateDrawingSession())
{
    //the line below:
    clds.DrawImage(item.Item1, new Vector2(randpos_x + imageborder + (int)((bounds.Width / 2) - imagebounds.Width / 2),
                                                                   randpos_y + imageborder + (int)((bounds.Height / 2) - imagebounds.Height / 2)));
}
```

It's still unclear to me what parameter is incorrect.

**Comment by getrou** [comment] 2023-01-27 04:26
What is item.Item1? It looks like it is an effect. If so, double check to make sure it being recreated when the device is lost. To prove this, you might try comparing the device of Item1 to the device of the drawing session to see if they are the same in the failure state.

**Comment by myokeeh** [comment] 2023-01-29 18:48
Yes, it's a `Transform2DEffect`. A bit of complication: It doesn't seem to be catching that particular exception per the recommendation. Come to think of it, it's never hit this `IsDeviceLost` condition.

```
 catch (Exception ee) when (sender.Device.IsDeviceLost(ee.HResult))
                    {
                        string sme = string.Empty;
                        if (clds.Device == sender.Device) { sme = "same"; }

                        App.TrackEvent1("LostDevice1", "Attempting RaiseDeviceLost " + sme);
                        sender.Device.RaiseDeviceLost();
                    }
```
