### ISSUE TITLE
Crash in CanvasRenderTarget Dispose after a SaveAsync

### ISSUE THREAD

**Issue by ankohanse** [Microsoft/Win2D#110] opened 2015-06-21 21:54 UTC
Am creating a live tile in a timer background thread.  As a result, I am dynamically creating a virtual CanvasControl and using it in a CanvasRenderTarget. After drawing the tile in a CanvasDrawingSession, I then can save the tile to a png. All as discussed in #68.

This worked fine in version 0.0.19. However, since updating to version 0.0.20, the thread crashes during the Dispose of the CanvasRenderTarget. When skipping the SaveAsync, the Dispose works fine.
Seems to be some kind of problem in the interaction between SaveAsync and the Dispose ???

Full test project that reproduces the problem:
https://www.dropbox.com/sh/6kcqeli678ilqbl/AADUY0O3RE6WnvcdFB3u9To7a?dl=0

code snipped from the background thread:

    Debug.WriteLine("Create DrawTarget");
    using (CanvasRenderTarget target  = new CanvasRenderTarget(glb_CanvasDevice, width, height, 96))
    { 
        Debug.WriteLine("Create DrawSession");
        using (CanvasDrawingSession session = target.CreateDrawingSession())
        {
            session.Clear( Colors.White );
            session.DrawText(text, width/2, height/2, Colors.Red);
        }
        Debug.WriteLine("Disposed DrawSession");

        // Save the icon here.
        await target.SaveAsync( ApplicationData.Current.LocalFolder.Path + "\\" + filename, CanvasBitmapFileFormat.Png).AsTask();
         Debug.WriteLine("Icon saved");
    }
    // This trace never occurs. Thread must end during the dispose ?
    // However, when you comment out the target.SaveAsync line, the dispose succeeds !
    // Problem in interaction between SaveSync and Dispose ???
    Debug.WriteLine("Disposed DrawTarget");

**Comment by shawnhar** [comment] 2015-06-22 20:02
Thanks for the report - we've managed to repro this issue and are investigating it now.

**Comment by damyanp** [comment] 2015-06-22 22:53
Thanks for the report with the very helpful self-contained repro project.

This was bug in Win2D and a fix is in commit e8df2eed396b88bbf3561dd78f99026f9127cea2.  Unfortunately, we just missed the deadline for this sprint's binary release, and so the fix will be in the next release - version 0.0.22.

In the meantime you can workaround it by changing the SaveAsync line to read:

    target.SaveAsync(ApplicationData.Current.LocalFolder.Path + "\\" + filename, CanvasBitmapFileFormat.Png).AsTask().Wait();

The cause of the issue is that when one uses 'await' on a background thread then each continuation after the await happens on a different thread.  So in this case, the SaveAsync happens on one thread, while the Debug.WriteLine and the Dispose() call happen on a second thread.

The bug was that Win2D was taking out a lock in the constructor of the SaveAsync IAsyncAction that would then be released when the IAsyncAction is destroyed.  The Dispose() call also needs to take out this lock.  It seems that the async action kept alive until the continuation completes (I suspect it is referenced on the stack, but I don't know enough of the details of how await / IAsyncAction works internally to be sure here).  So now you have a deadlock - the Dispose() can't complete until the async action is destroyed, and the async action can't be destroyed until the Dispose() completes.

Adding the Wait() call avoids this issue because that keeps all the code executing on the same thread.  

Thanks again for bringing this to our attention.

**Closed** 2015-06-22 22:54 UTC
