### ISSUE TITLE
Microsoft.Graphics.Canvas.Text.CanvasTextLayout Constructor throws exception

### ISSUE THREAD

**Issue by mscherotter** [Microsoft/Win2D#535] opened 2017-07-05 23:32 UTC
I am seeing an exception in a HockeyApp crash reports for an app that I have where this call that I am making in my code is throwing an exception with the detail below:
Microsoft.Graphics.Canvas.Text.CanvasTextLayout..ctor(Graphics.Canvas.ICanvasResourceCreator resourceCreator, String textString, Graphics.Canvas.Text.CanvasTextFormat textFormat, Single requestedWidth, Single requestedHeight)

[CanvaTextExceptionLog.txt](https://github.com/Microsoft/Win2D/files/1126323/CanvaTextExceptionLog.txt)

Illegal operation attempted on a registry key that has been marked for deletion. (Excep_FromHResult 0x800703FA) 

I have attached the exception log: Surface Pro 4 running Windows10.0.15063.413 

Any suggestions?

Michael

**Comment by clandrew** [comment] 2017-07-05 23:38
Thank you for this report, Michael. Would you be able to share your app with some details of how you run it, so we can reproduce the problem?

**Comment by mscherotter** [comment] 2017-07-05 23:41
I haven't been able to reproduce it, I just saw this report in my HockeyApp crash reporting.

The app is in the store as Journalist:

1. Install the free Journalist app in the store 
2. Start the app and create a new journal
3. On a journal page, press the + button at the bottom and add Text
4. Type something and click outside the text

**Comment by clandrew** [comment] 2017-07-05 23:50
Thanks. I'll look into this and reply back with what I find.

**Comment by clandrew** [comment] 2017-07-06 06:25
I downloaded the Journalist app and ran through the repro steps several times but was not able to reproduce a crash. I'm using version 1.1.207.0 of the app, which matches the log here.

Looking at the exception itself- 
Generally, creating and manipulating DirectWrite (Win2D text) objects such as text layouts will touch registry keys. In particular, DWrite can read/enumerate registry keys when reading system fonts if this is not being done in the font cache. If another application on the system juuust happened to delete a key at the very same time DWrite was reading it, it could cause this error. The odds of this aren't high, but hypothetically it's possible. One (although not foolproof) idea is to re-try creating the resource after waiting a little bit. It's not a great way to fix it, but can be an option for isolating this as the problem.

Besides that, something else seems suspicious in that log. I see the innermost frames look like
...
Journalist.UWP!<BaseAddress>+0x195521e
Microsoft.Graphics.Canvas.Text.CanvasTextLayout..ctor(Graphics.Canvas.ICanvasResourceCreator resourceCreator, String textString, Graphics.Canvas.Text.CanvasTextFormat textFormat, Single requestedWidth, Single requestedHeight)
Journalist.Data.Text.CreateResourcesAsync(Graphics.Canvas.ICanvasResourceCreator resourceCreator)
Journalist.UWP!<BaseAddress>+0x1b015fd
...

This- unless I'm really missing something- implies CanvasTextLayout's ctor was calling back into the app. If possible, it'd be good to get more information in the future about what was happening there. Symbols, or some logging as to what that call was.

**Comment by clandrew** [comment] 2017-07-06 18:00
Got it- thank you for that code snippet.

Adding a try/catch could mitigate the issue by preventing an app crash, provided your app is set up to cope with the text layout being null.

A better approach would be to get more information about what happened. In particular, we need to be able to understand

- What piece of Journalist code is CanvasTextLayout's ctor calling into? Is this real, or is this just a garbage stack?
- What, specifically, within CanvasTextLayout's ctor is throwing the exception?

I think getting symbols for app code could help answer these questions. Aside from that, without a repro or anything more to go on, there isn't really any way for us to chase this down further. So if you work around it and never see it again, great! Otherwise, I hope getting additional information will help lead to some clues and we can investigate more from there.

**Comment by shawnhar** [comment] 2017-08-14 15:31
Closing issue due to lack of repro.   Feel free to reactivate if you are able to get us more info to understand this.

**Closed by shawnhar** 2017-08-14 15:31 UTC
Labels: need info
