### ISSUE TITLE
The presence of old Visual C++ distributables makes Win2D act unreliably

### ISSUE THREAD

**Issue by rsheptolut** [Microsoft/Win2D#449] opened 2016-10-31 10:46 UTC
Well, first I'll confess I don't have enough info on this. I've found a workaround for the issue, and I thought it might help other people who struggle with this issue. But I can't really describe the issue in perfect detail. Anyway:

We develop a C# windows 8.1 "metro" app that uses the Win2D.win81 1.19.0 nuget package for rendering fancy price tags. It works just fine on most machines: win 8.1 workstations, win 8.1 tablets, and win 10. But today I've discovered that it doesn't work right on my home pc. Although both at work and at home I use Visual Studio 2015 update 3 + hotfixes.

It crashes if there are too much win2d-using controls on the screen OR if we call Invalidate() on any canvas. That means our app crashes every time after launch, because we do both things every time. Visual Studio does not give me any useful info to debug it. It only displays: "An unhandled exception occured" and "The debugger is attached to x.exe, but not configured to debug this unhandled exception". But even if I detach my current debugger, I have no luck starting up a JIT debugging session. 

I've tested a lot random ways to fix it, but then I remembered that win2d depends on some magic "Visual C++ runtime" somewhere in the system, and I've installed a lot of games from Steam lately )) Before installation and launch they sometimes install / update Visual C++ redistributables.

So naturally, after I've removed a couple of Visual C++ 2005 & 2008 packages - everything started working normally! No more crashes!

So, maybe someone will need that. I would've. Spent a couple of hours guessing. Maybe devs also have something to say or do about it, idk.

Specifically, I removed those packages (as seen in "Add/remove programs" control panel menu):
Microsoft Visual C++ 2005 Redistributable
Microsoft Visual C++ 2005 Redistributable (x64)
Microsoft Visual C++ 2008 Redistributable - x86 9.0.21022
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.4148

And I still have 12 Microsoft Visual C++ rows remaining after that in my "Add/remove programs" control panel menu (what a mess).

**Comment by shawnhar** [comment] 2016-10-31 13:10
I think it's very unlikely this was actually the root cause of your issue.  The 2005 and 2008 C runtimes will not affect running of Win2D apps - those are only loaded into desktop apps that were built with much older compilers.  It is normal to have many different C runtimes installed at the same time (I hope you didn't break any other apps by removing these).

I haven't seen this issue before so not sure what the problem might be.  The inability to debug sounds like possibly a problem with your Visual Studio install on this machine?  I almost wonder if it could be a low memory situation, or possibly close to some other resource limit.  When did you last reboot this PC?

**Comment by rsheptolut** [comment] 2016-10-31 13:47
@shawnhar I've performed a reboot, unloaded all apps that I can think of from memory. I have 16 GB memory in my system, and my OS is pretty fresh and stable. I tried with and without debugging (no Visual Studio running at all). Without debugging, the app just hangs and crashes silently after 1 second. Not ability to debug has something to do with the fact that the app is managed and encounters an unmanaged exception: I have no idea how to correctly debug these. Thanks, Microsoft, for making .Net development so easy that I actually know nothing about the unmanaged world.

So I'm pretty sure the removal of the runtimes helped (not sure if it is the _root_ cause though), because I intentionally tested the app after every change. Before removing the distributables it crashed and after I removed them - everything had been working fine ever since.

Yeah, maybe some programs or old games might not work now, in that case I'll install some of the needed distribs back, and check again how our app is doing ) I can probably do that now, if you wish (and if I find where to download such old distribs)

**Comment by shawnhar** [comment] 2016-10-31 16:29
I'm skeptical that having these unused C runtimes installed was anything more than coincidence, but we'll be happy to take a look if you can figure out how to reproduce the issue.  Without repro steps, I'm afraid there's nothing we can do here though.

**Comment by rsheptolut** [comment] 2016-10-31 16:51
@shawnhar you're right to have doubts, it seems weird. I'll soon find time to install the redistributables back and see what happens. You know, just in case I was right.

**Comment by shawnhar** [comment] 2016-11-09 20:48
Closing due to lack of repro steps.  Feel free to reactivate if you are able to find a way we can repro what you are seeing.

**Closed by shawnhar** 2016-11-09 20:48 UTC
Labels: need info
