### ISSUE TITLE
Blurry Output if Scale on DrawingSession after Transform2DEffect

### ISSUE THREAD

**Issue by spass2000** [Microsoft/Win2D#296] opened 2016-03-05 15:30 UTC
Hello

i'm using a global Scale/Zoom on my DrawingSession on the property Transform. 
If this scale is set like in the example below to "2" than the second Rectangle which is rotaded with the Transform2DEffect is very blurry. How can i fix this?

rgds Mike

`
private void canvas_Draw(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasDrawEventArgs args)
        {
            args.DrawingSession.DrawText("Hello, World!", 100, 100, Colors.Black);
            args.DrawingSession.Transform = Matrix3x2.CreateScale(2f);                  
            args.DrawingSession.DrawText("Hello, World!", 40, 30, Colors.Green);
            var r = new Rect(0, 0, 100, 100);
            CanvasCommandList cl = new CanvasCommandList(sender);
            using (CanvasDrawingSession clds = cl.CreateDrawingSession())
            {
                var g1 = CanvasGeometry.CreateRoundedRectangle(args.DrawingSession, r, 5f, 5f);
                clds.FillGeometry(g1, Colors.Honeydew);
                clds.DrawGeometry(g1, Colors.Black, 0.2f);
                clds.DrawText("TEST", r, Colors.Black, ctf);
            }
            args.DrawingSession.DrawImage(cl, 100, 100, r);

            var e1 = new Transform2DEffect
            {
                Source = cl,
                TransformMatrix = Matrix3x2.CreateRotation(DegreesToRadians(45))
            };
            args.DrawingSession.DrawImage(e1, 300, 100);  // Blurry Output
        }`

Scale set to 2:

![screenshot142](https://cloud.githubusercontent.com/assets/5301939/13548370/fd04d394-e2ee-11e5-97ed-efe03345d31e.png)

**Comment by shawnhar** [comment] 2016-03-07 15:27
This is due to the difference between vector and image based rendering techniques.  CanvasCommandList and CanvasGeometry are vector drawing APIs, but image effects such as Transform2DEffect operate on rasterized bitmap images.

When your code feeds a command list into the transform effect, Direct2D will rasterize the vector graphics into a bitmap format.  The problem is that your vector shape contains a very thin (0.2 wide) line.  This will be antialised down to less than full brightness during rasterisation.  Then the rotation takes place, which will further filter the line, and finally the drawing session transform scales it up by 2x - but at this point detail has already been lost because you applied bitmap operations to an image that was only half the resolution of your final output.

Options to fix this:

1. Combine the rotation and 2x scale into args.DrawingSession.Transform, so you no longer need Transform2DEffect - now the entire drawing takes place in vector realm so rotating lines less than 1 pixel in width does not produce any loss of detail.

2. Or move your 2x scale from args.DrawingSession.Transform to clds.Transform - this approach is still using an image based rotation, but the scale-up happens before vector to image conversion, so less detail is lost.

Hope that helps,

**Comment by shawnhar** [comment] 2016-03-14 13:44
Closing issue as I believe this question has been answered.  Feel free to reactivate if you have further questions.

**Closed by shawnhar** 2016-03-14 13:44 UTC
Labels: question
