### ISSUE TITLE
DrawFromSpriteSheet causing visual artifacts

### ISSUE THREAD

**Issue by Thraka** [Microsoft/Win2D#326] opened 2016-04-07 15:52 UTC
Drawing lots of tiny sprites overlaid on each other (via DrawFromSpriteSheet) seems to cause this weird behavior.

Source code [here](https://onedrive.live.com/redir?resid=58D9BBD7617BF383!242270&authkey=!AISBSWpS2KtCeCE&ithint=file%2czip).

![](https://r0rb6a-bn1305.files.1drv.com/y3mIRdYY7n9-53yA6HwjMix2H6Ua-sEHXlVLYDvkAj9qnWGDmpUvF0N1-V4YlVVUel_c9urtXCLXXV4qMR7nXSVPGhxOBuU-8wfEDW6WZ1Uw26_pNv_DUzSFA2iYAHizG5Lxl3TwEpBVlBZ-gyf3ORZDERzLHpbKt4S5DsrLSFt074/win2d-bad.gif?psid=1)

**Comment by shawnhar** [comment] 2016-04-07 17:03
Interesting, thanks for the report and great repro app!

I see the same thing both on a real GPU and using WARP, so it's not a driver bug.

Issue seems to be triggered by the ellipse followed by sprite drawing.  It does not flicker if I remove the ellipse.

As a temporary workaround, calling DrawingSession.Flush before CreateSpriteBatch avoids the problem.  That adds some perf overhead, but may be useful to unblock you until we can get the actual bug fixed?

**Comment by Thraka** [comment] 2016-04-07 17:10
I'm just messing around, so not blocking. Just looking at other ports for [SadConsole](http://github.com/Thraka/SadConsole)

**Comment by shawnhar** [comment] 2016-04-07 20:40
Ok, we root caused this.  It is a Direct2D bug that will be fixed in the next update to Windows.  In fact, it'll already be fixed if you run a recent Win10 insider OS build.

Workaround is indeed as I guessed above - place a Flush after drawing geometry (in this case the ellipse) but before drawing the sprites.

**Comment by shawnhar** [comment] 2016-08-04 04:29
This issue is fixed in the Windows 10 Anniversary Update.

**Closed by shawnhar** 2016-08-04 04:29 UTC
Labels: bug, external
