### ISSUE TITLE
Is there some problem on Windows10 1511?

### ISSUE THREAD

**Issue by omanuke** [Microsoft/Win2D#204] opened 2015-12-15 02:34 UTC
I upgraded to Windows 10 1511 recently.
After that,while using my app( which use Win2D),Windows raised message often about that GPU driver has stopped. Sometimes my app become no response and I can't kill it by Task Manager.
Is there some known issue?
Regards,

**Comment by 13thsymphony** [comment] 2015-12-15 18:05
Hi omanuke,

At first glance this sounds like a GPU driver issue. Have you checked to ensure your driver is the latest available version? Many GPUs have drivers available on Windows Update, but you may need to go to the IHV's website (Intel, Nvidia, AMD, etc).

Also, can you run dxdiag.exe and send us the logs (Save All Information)? Do this before updating your driver.

**Comment by omanuke** [comment] 2015-12-16 00:10
It seems like not latest one.
I haven't update it yet.
If u has something to investigate, I' ll do it.

https://downloadcenter.intel.com/download/25313/Intel-HD-Graphics-Driver-for-Windows-7-8-1-10-3rd-Gen-BYT-
[DxDiag.txt](https://github.com/Microsoft/Win2D/files/63368/DxDiag.txt)

**Comment by 13thsymphony** [comment] 2015-12-16 00:45
Thanks for the info. Since this is a Surface Pro 3, driver updates should come down automatically through Windows Update. You can manually get the latest SP3 all-in-one driver package here:
https://www.microsoft.com/en-us/download/details.aspx?id=38826

I'm not aware of any specific issue with your current configuration, so you can go ahead and update the driver and see if anything changes.

**Comment by shawnhar** [comment] 2015-12-21 19:42
Closing issue as there does not appear to be any Win2D bug here.

Please let us know if you are able to share instructions on how to reproduce the problem once you are using latest drivers.

**Closed by shawnhar** 2015-12-21 19:42 UTC
