### ISSUE TITLE
Wind2D / Direct2D Interop

### ISSUE THREAD

**Issue by jeromebjerome** [Microsoft/Win2D#146] opened 2015-08-31 11:23 UTC
Hello,

This is a basic sample C++ Universal App (VS 2015), using Win2D plugin and testing interoperability between Win2D and Direct2D.  
•	I only defined the Win2D entry for the canvas rendering operation.
•	The sample draws an ellipse and a geometry.
o	The ellipse is displayed correctly, when displayed alone, but when the geometry is added, it causes a systematic exception (see image).
•	I played with adding/removing the different Release but it did not change the result.
•	If the FillGeometry is commented out, there is no exception raised.

I may have missed something basic or important, sorry in advance.

void MainPage::OnRender(Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl^ sender,
	Microsoft::Graphics::Canvas::UI::Xaml::CanvasDrawEventArgs^ args)
{
	ComPtr<ID2D1RenderTarget> target = GetWrappedResource<ID2D1RenderTarget>(args->DrawingSession);
	ID2D1RenderTarget *pTarget = target.Get();
	if (pTarget) {

		// Draw an ellipse : OK
		// ====================

		Windows::UI::Color color;
		color.A = 255;
		color.R = 0;
		color.G = 0;
		color.B = 255;
		args->DrawingSession->FillEllipse(300.f, 300.f, 150.f, 100.f, color);

		// Draw a geometry : Not OK
		// ========================

		ID2D1Factory* factory;
		ID2D1PathGeometry *geometry = NULL;
		ID2D1GeometrySink *pSink = NULL;
		ID2D1SolidColorBrush* pBrush = NULL;

		D2D1CreateFactory(D2D1_FACTORY_TYPE_SINGLE_THREADED, &factory);
		factory->CreatePathGeometry(&geometry);
		geometry->Open(&pSink);

		pSink->SetFillMode(D2D1_FILL_MODE_WINDING);

		pSink->BeginFigure(
			D2D1::Point2F(346, 255),
			D2D1_FIGURE_BEGIN_FILLED
			);
		D2D1_POINT_2F points[5] = {
			D2D1::Point2F(267, 177),
			D2D1::Point2F(236, 192),
			D2D1::Point2F(212, 160),
			D2D1::Point2F(156, 255),
			D2D1::Point2F(346, 255),
		};

		int pts_nb = ARRAYSIZE(points);
		pSink->AddLines(points, pts_nb);
		pSink->EndFigure(D2D1_FIGURE_END_CLOSED);

		pSink->Close();
		pSink->Release();

		pTarget->CreateSolidColorBrush(
			D2D1::ColorF(D2D1::ColorF::CornflowerBlue),
			&pBrush
			);

		pTarget->FillGeometry(
			geometry,
			pBrush,
			NULL
			);

		pBrush->Release();

		geometry->Release();

		factory->Release();
	}
}

![exception](https://cloud.githubusercontent.com/assets/13735023/9577623/08689f12-4fe3-11e5-8535-a2448b1889ff.png)

**Comment by jeromebjerome** [comment] 2015-08-31 11:34
Please use this code instead (Ellipse using pTarget)

void MainPage::OnRender(Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl^ sender,
	Microsoft::Graphics::Canvas::UI::Xaml::CanvasDrawEventArgs^ args)
{
	ComPtr<ID2D1RenderTarget> target = GetWrappedResource<ID2D1RenderTarget>(args->DrawingSession);
	ID2D1RenderTarget *pTarget = target.Get();
	if (pTarget) {

		ID2D1Factory* factory;
		ID2D1PathGeometry *geometry = NULL;
		ID2D1GeometrySink *pSink = NULL;
		ID2D1SolidColorBrush* pBrush = NULL;

		pTarget->CreateSolidColorBrush(
			D2D1::ColorF(D2D1::ColorF::CornflowerBlue),
			&pBrush
			);

		// Draw an ellipse : OK
		// ====================

		D2D1_ELLIPSE ellipse;
		ellipse.point.x = 300.f;
		ellipse.point.y = 300.f;
		ellipse.radiusX = 150.f;
		ellipse.radiusY = 100.f;

		pTarget->FillEllipse(ellipse, pBrush);

		// Draw a geometry : Not OK
		// ========================

		D2D1CreateFactory(D2D1_FACTORY_TYPE_SINGLE_THREADED, &factory);
		factory->CreatePathGeometry(&geometry);
		geometry->Open(&pSink);

		pSink->SetFillMode(D2D1_FILL_MODE_WINDING);

		pSink->BeginFigure(
			D2D1::Point2F(346, 255),
			D2D1_FIGURE_BEGIN_FILLED
			);
		D2D1_POINT_2F points[5] = {
			D2D1::Point2F(267, 177),
			D2D1::Point2F(236, 192),
			D2D1::Point2F(212, 160),
			D2D1::Point2F(156, 255),
			D2D1::Point2F(346, 255),
		};

		int pts_nb = ARRAYSIZE(points);
		pSink->AddLines(points, pts_nb);
		pSink->EndFigure(D2D1_FIGURE_END_CLOSED);

		pSink->Close();
		pSink->Release();


		pTarget->FillGeometry(
			geometry,
			pBrush,
			NULL
			);

		pBrush->Release();
		geometry->Release();
		factory->Release();
	}
}

**Comment by shawnhar** [comment] 2015-08-31 14:14
The code you posted here doesn't compile - you're missing the template specializations for ComPtr and GetWrappedResource() calls.

Having fixed that, the exception message string (visible in the debugger watch window) tells what the problem is:

    errorMessage	0x009ce240 L"Objects used together must be created from the same factory instance.\r\n"	Platform::String ^

You need to create your geometry from the same factory Win2D is using (which you can query from any ID2D1Resource) rather than creating a different factory from scratch.

**Comment by shawnhar** [comment] 2015-09-03 16:29
Closing on the assumption that this resolved your problem - let us know if you are still having issues.

**Closed by shawnhar** 2015-09-03 16:29 UTC
