### ISSUE TITLE
Consecutive SpriteBatches using same CanvasBitmap fails to render (without assistance)

### ISSUE THREAD

**Issue by ZodmanPerth** [Microsoft/Win2D#489] opened 2017-01-31 13:26 UTC
I'm currently playing with parallax scrolling of tilemaps in overlapping layers.  I'm using a component pattern to define an array of tilemap components, each managing the drawing of it's own layer using a spritebatch.

I've noticed that when I use tilemaps that reference the same CanvasBitmap, if those tilemaps are drawn one after the other then neither is drawn at all.  If a tilemap from a different source is drawn in between, all tilemaps are drawn correctly.

I also note that when I flush the DrawingSession after disposing each spritebatch, the consecutive scenario is drawn correctly.

I'm not sure if this is a bug or a known restriction with the use of spritebatches.  At present I'm forced to flush the DrawingSession to get the effect I am after; is there any performance issues with flushing in this way?

I'm using Win2D v1.20.0.

**Comment by shawnhar** [comment] 2017-01-31 15:07
This is a dupe of #407.  It's a bug in the OS, and will be fixed in the next version of Windows.

A workaround is to draw something else (such as a zero sized rectangle) in between the two sprite batches.

**Closed** 2017-01-31 15:08 UTC

**Comment by ZodmanPerth** [comment] 2017-02-01 12:48
Egad, so it is.  I'll try the zero size rectangle workaround.  Cheers.
