### ISSUE TITLE
AccessViolation

### ISSUE THREAD

**Issue by ju2pom** [Microsoft/Win2D#116] opened 2015-07-10 21:03 UTC
We are developing an image application for windows 8.1 using Win2D.
In this application images are split in tiles.

When panning or zooming our list of tiles changes (they basically are WritableBitmaps).
And each time this list change, we create one CanvasImage per tile and draw those tiles in a CanvasControl.

It seems to globally work (it a bit slow but there is room for optimization I guess).
Panning is ok, but after zooming out six times we face an exception "AccessViolation" on the following piece of code:
```c#
this.Bitmap = CanvasBitmap.CreateFromBytes(
        device,
        this.Tile.Bitmap.PixelBuffer.ToArray(),
        (int)this.Tile.Area.Width,
        (int)this.Tile.Area.Height,
        DirectXPixelFormat.B8G8R8A8UIntNormalizedSrgb);
```
![accessviolation_win2d](https://cloud.githubusercontent.com/assets/3799294/8629023/d68c7ae4-2757-11e5-8a60-dcca0780fcc0.png)

**Comment by shawnhar** [comment] 2015-07-10 21:06
What is your width and height, and what is the size of the pixel buffer array, when the crash occurs?

**Comment by ju2pom** [comment] 2015-07-10 21:09
Width and height are both 256 and the buffer length is 262144.
During the crashing scenario I can see that 45 instances are created and disposed.

**Comment by shawnhar** [comment] 2015-07-10 21:12
Can you put together a repro app so we can run and debug this issue?

thx

**Comment by ju2pom** [comment] 2015-07-10 21:30
I'm not sure I can isolate the issue in a small app and I don't think I can disclose our code.
I tried to compile win2d from sources to debug the issue but when trying to step in CanvasBitmap.CreateFromBytes Visual Studio ask for windows.ui.xaml.pdb.

How could I investigate the issue, do you have any clue/lead?

**Comment by ju2pom** [comment] 2015-07-10 21:34
Here is the draw method:
```c#
private void OnDraw(CanvasControl sender, CanvasDrawEventArgs args)
    {
      lock (this.locker)
      {
        if (this.Tiles != null && this.Tiles.Any())
        {
          args.DrawingSession.Antialiasing = CanvasAntialiasing.Aliased;
          foreach (TileHost host in this.tileHosts)
          {
            args.DrawingSession.DrawImage(host.Bitmap, this.Transform.TransformBounds(host.Tile.Area));
          }
        }
      }
    }
```
I added the lock in case it can help, but sadly no.

**Comment by shawnhar** [comment] 2015-07-10 21:40
As long as you turn on mixed mode debugging, you should be able to step inside the native Win2D code.   Or just turn on first chance exceptions to break directly at the spot where it is failing.

Unfortunately I will need some kind of repro app to be able to debug this - there's not much I can do if you aren't able to provide that.

**Comment by shawnhar** [comment] 2015-07-14 18:23
Closing because this issue is not actionable for us without some way to reproduce the crash.  Please reactivate if you are able to share instructions or code showing how to repro.

**Closed by shawnhar** 2015-07-14 18:23 UTC
