### ISSUE TITLE
Device lost cause a crash app with win2D 

### ISSUE THREAD

**Issue by pkostaki** [Microsoft/Win2D#508] opened 2017-04-11 13:35 UTC
Hello,
Win2d crashes while device lost occurs. I have create a blank uap appication and place Win2d CanvasControl on page without any logics. Then made few calls(2-6) of command "dxcap -forcetdr" and crash appeared.
device info attached.[DxDiag.txt](https://github.com/Microsoft/Win2D/files/913332/DxDiag.txt)
Thanks.

**Comment by shawnhar** [comment] 2017-04-11 17:07
Hi,

I cannot repro this on my machine (using the Win2D SimpleSample).  Can you give more information about how the app crashes?  Callstack, crash dump, etc?

I notice you are running on older Intel graphics drivers, so it is possible this could be related to issue #300, which was fixed in the 4550 drivers.

**Comment by pkostaki** [comment] 2017-04-12 09:02
Here more details about issue.
Callstack:
[callstack.txt](https://github.com/Microsoft/Win2D/files/915950/callstack.txt)

Build&dump will temporary available here:
  https://drive.google.com/file/d/0B8QAn7MMxNZPZFVaRzA5cVRzdFU/view?usp=sharing
  https://drive.google.com/file/d/0B8QAn7MMxNZPZEpUS2JRNmlyekE/view?usp=sharing

Also able repro issue with last driver version. Updated device info file attached:
[DxDiag3.txt](https://github.com/Microsoft/Win2D/files/915974/DxDiag3.txt)

**Comment by shawnhar** [comment] 2017-04-13 18:34
Hi,

Thanks for the dump.  Unfortunately still no luck reproing this locally.   I believe you are working on a project with an internal Microsoft team though?  Can I ask that you reach out through them so we can get hooked up on internal email and get some additional diagnostics from the system you are able to repro this on?

Thanks,

**Comment by pkostaki** [comment] 2017-04-14 13:55
Hello,
We are in process now.

Here one more, maybe more informative callstack:
[callstack_devicelost.txt](https://github.com/Microsoft/Win2D/files/922195/callstack_devicelost.txt)

Thanks.

**Comment by shawnhar** [comment] 2017-04-14 14:41
That's a completely different callstack from the first crash dump.  Do you see any consistency from one repro to another, or is this crashing in a different place every time?

**Comment by pkostaki** [comment] 2017-04-17 07:37
This callstack from another app's launch (version x86), received under device lost. Yes, receved 1-2 callstacks. Noticed, different callstacks received for version of the same app but compiled for different architecture x86, x64.

**Comment by shawnhar** [comment] 2017-04-17 13:02
Different callstacks suggests you may be looking at more than one root cause.  Or possibly it's a memory corruption type issue, in which case the location of the crash may be unrelated to the original cause.

When you repeat this repro, do you see one of a smallish set of callstacks over and over again, or is it different every time?

**Comment by pkostaki** [comment] 2017-04-19 11:44
I met only such two types of callstacks in current os version.

**Comment by pkostaki** [comment] 2017-04-26 09:00
Hello, 
Extra details about this issue in RS2 os version. 
•	The crash is not repro if stay on page and make series of calls "dxcap -forcetdr".
•	The crash is repro while navigate between pages and call "dxcap -forcetdr". The exception: Not_enough_storage_is_available_to_complete_this_operation. 
This was reproduce on blank app under first call of "dxcap -forcetdr"(to exclude problems with memory and memory leaks).
Whole information available here (device info, source, build, callstack):
 https://drive.google.com/open?id=0B8QAn7MMxNZPSUZSeDNyOGhJRHc

**Comment by shawnhar** [comment] 2017-04-26 17:03
That looks like a completely different crash yet again.

Backing up to my earlier comment:

> I believe you are working on a project with an internal Microsoft team though? Can I ask that you reach out through them so we can get hooked up on internal email and get some additional diagnostics

**Comment by pkostaki** [comment] 2017-04-27 08:55
Yes, callstacks differ. I point up os version, it's meaningfully. Previous result was occured at RS1
Ms team already notified.
Thanks

**Comment by shawnhar** [comment] 2017-05-26 22:15
I'm going to close this issue as it is not actionable for us without some way to repro.  Please get in touch through your internal Microsoft contacts if you still need help with this.

**Closed by shawnhar** 2017-05-26 22:15 UTC
Labels: need info
