### ISSUE TITLE
System.TypeLoadException

### ISSUE THREAD

**Issue by ankohanse** [Microsoft/Win2D#59] opened 2015-04-16 03:49 UTC
Not sure what the best platform is to post questions on technical problems....

I have included Win2D v 0.0.16 via NuGet in a Windows Phone project. However, when using CanvasTextLayout and CanvasGeometry, I get errors like:

{System.TypeLoadException: Requested Windows Runtime type 'Microsoft.Graphics.Canvas.Text.CanvasTextLayout' is not registered. ---> System.Runtime.InteropServices.COMException: Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
   --- End of inner exception stack trace ---
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Microsoft.Graphics.Canvas.Text.CanvasTextLayout..ctor(ICanvasResourceCreator resourceCreator, String textString, CanvasTextFormat textFormat, Single maximumLayoutWidth, Single maximumLayoutHeight)
   at PVOutput.HubPage.CanvasX_Draw(CanvasControl canvas, CanvasDrawEventArgs args, Int32 iDayX)}

I do not see these classes in the generated AppxManifest.xml. 
Bug or am I missing a vital step somewhere ?

**Comment by shawnhar** [comment] 2015-04-17 02:47
I cannot repro these issues.  Can you share more info about what type of project you are using (what template did you start from?  ARM or x86, etc?)  and what version of Visual Studio you are using?

**Comment by ankohanse** [comment] 2015-04-17 05:49
Hi Shawn,

 

Project is in Visual Studio Express 2013 Update 4

Debug x86, in a Universal App (although for now I am only using the WindowPhone subproject)

 

Special condition is that there is some draw code in a RunTime component. 

That all works fine for most draw functions, like DrawText, DrawLine and DrawCircle. But starts giving issues when you start using CanvasGeometry in there.

My intention is to share the drawing code with a background task to generate a dynamic start-screen icon (like the Weather app does).

 

I have created a simple test-app that demonstrates the issue. See attachment, I have left the NuGet Win2D 0.0.16 package out of the zip to limit its size.

 

Problem is that once the problem occurs (by de-commenting some code in the runtime component) it keeps occurring, even when you comment-out the code again. The test project is in that state now…

 

Kind regards,

Anko

**Comment by shawnhar** [comment] 2015-04-17 17:24
Unfortunately I am not able to see your attachment - I don't think github supports attaching files directly to an issue, so it seems it just dropped that.

Could you upload the test app somewhere and post a link, please?

**Comment by ankohanse** [comment] 2015-04-18 05:11
Hi Shawn,

 

Try this one:

https://www.dropbox.com/sh/6kcqeli678ilqbl/AADUY0O3RE6WnvcdFB3u9To7a?dl=0

 

Kind regards,

Anko Hanse

**Comment by JohnnyWestlake** [comment] 2015-04-20 06:49
Too add, I get a similar exception when I built Win2D using VS 2015 CTP on Windows 10. I could use the Win2D in my own project, but other developers on my team using VS 2013 on Windows 8.1 get those exact type load exceptions about class' not being registered (though in my case I assume it's because I'm messing with unsupported configurations)

**Comment by shawnhar** [comment] 2015-04-20 14:09
Thanks.  I downloaded the repro ok, so we'll take a look.

**Comment by damyanp** [comment] 2015-04-20 17:27
ankohanse,

The issue here is that you're trying to consume Win2D from a portable class library (this if what you get when you choose "Universal Apps -> Windows Runtime Component (Portable for Universal Apps)).

Although these work for pure managed code, since Win2D is native code you need to have a separate library for each target device (in much the same way that you need to have a separate project for your Windows App and Windows Phone App).

In short: you can't use Win2D from a portable class library.

However, we do expect it to be usable it from a runtime component specific to the platform.  

Unfortunately, I just tried this and it runs into build problems if you also reference the runtime component from something else that uses Win2D (such as your app). 

I've added an item to our backlog for making sure Win2D can be used from background tasks, and part of this will involve fixing this issue.

Sorry I can't provide a better answer at the moment - but we'll get to work on ensuring that this scenario works!

**Comment by ankohanse** [comment] 2015-04-20 20:12
Hi Damyan and Shawn,

Thanks for looking into this. Your analysis sounds very logical and I will eagerly await a fix that makes it possible to run Win2D from a background task.

P.S. I think the Win2D library is very easy to use and really fills a void. Keep up the great work!

**Comment by damyanp** [comment] 2015-04-21 22:35
Version 0.0.17 will contain fixes that will allow you to use Win2D from within a Windows Runtime Component.

However, there is a bug in VS2013 Update 4 which causes problems when you try and reference this component (you'll get runtime typeload exceptions, much like you were originally seeing with the PCL).  This bug is fixed in VS2013 Update 5 (and VS2015).

**Comment by clandrew** [comment] 2015-04-30 01:37
This has been fixed with the latest release, version 0.0.17.

**Closed by clandrew** 2015-04-30 01:37 UTC

**Comment by skendrot** [comment] 2015-07-23 06:08
I'm getting this error with VS2013 Update 5 with the following code:
_image = await CanvasBitmap.LoadAsync(sender, ImageSource); // I've tried string, Uri, and Stream

I'm getting the following error:
An exception of type 'System.TypeLoadException' occurred in AppName.WindowsPhone.exe but was not handled in user code

Additional information: Requested Windows Runtime type 'Microsoft.Graphics.Canvas.CanvasBitmap' is not registered.

**Comment by damyanp** [comment] 2015-07-23 16:24
Can you provide more details about what sort of project you're using Win2D from?

Are you trying to use Win2D from a Portable Class Library?  This isn't supported - you need to use it from a Windows Runtime Component.

If not, then could you share a repro with us please?  Thanks.

**Comment by TomasHubelbauer** [comment] 2015-09-08 10:52
Hey, this happened to me as well. I've been using `Win2D.uwp` Nuget package in version 1.3.0 and I installed it with zero issues, but when I copy-pasted in some code I use for generating QR codes:

```cs
var canvasDevice = CanvasDevice.GetSharedDevice();
var canvasImageSource = new CanvasImageSource(canvasDevice, width, height, 96);
using (var drawingSession = canvasImageSource.CreateDrawingSession(Color.FromArgb(255, 255, 255, 255)))
{
  for (var y = 0; y < height; y++)
  {
    for (var x = 0; x < width; x++)
    {
      if (bitMatrix.get(x, y))
      {
        drawingSession.DrawRectangle(x, y, 1, 1, Color.FromArgb(255, 0, 0, 0));
      }
    }
  }
}
```

The application broke at the `var canvasDevice = CanvasDevice.GetSharedDevice();` line with `TypeLoadException` wrapping the registration exception. I suspect just whatever Win2D object was hit next caused the exception, not `CanvasDevice` explicitly.

**What solved this for me** was to go to project properties in the UWP application, select the *Build* tab and switching the platform target to AMD from x86, building, obviously failing to publish and then switching back to x86. Then it just worker. Not sure exactly what the root issue is, but maybe this will help someone.

**Comment by shawnhar** [comment] 2015-09-08 13:41
Interesting.  Please let us know if you ever manage to figure out a reliable way to repro this.  It's defiantly something we'd want to pass on to the Visual Studio team, but unfortunately not much they can do without some way to repro :-(

**Comment by TomasHubelbauer** [comment] 2015-09-08 13:47
I will let you know if I have a reliable repro, but this happens kind of randomly, so no promises I will get one.

**Comment by Ingerdev** [comment] 2016-04-28 01:50
28.04.2016. MSVS 2015 update 2, nuget package Win2d.UWP 1.17.0, same "type is not registered" exception when created CanvasControl runtime

**Comment by damyanp** [comment] 2016-04-28 16:29
@Ingerdev - can you share a project that reproduces this issue please?

**Comment by dengfan** [comment] 2016-04-30 15:49
@TomasHubelbauer Thank you very much, I used you idear and it fixed, thanks again!

**Comment by Ingerdev** [comment] 2016-05-02 20:16
@damyanp sorry but i cant share sources. However, i can allow you remote debug this project and examine all necessary properties. I tried to reproduce this bug on fresh new project without success.

**Comment by damyanp** [comment] 2016-05-02 20:30
@Ingerdev - if you can send us a project that reproduces this issue then I'll be happy to investigate further.

**Comment by Ingerdev** [comment] 2016-05-02 22:10
Interesting, today I played with it and switching various compiling modes (.net native/net/release/debug/x86/x64) suddenly eliminated this error in all modes.

**Comment by jyoungl6** [comment] 2016-06-11 02:16
I am having the exact same problem as IngerDev. I'm using the package in a C++/CX UWP app. Running as x64 is fine. Running as x86 and I get a "WinRT information: Class not registered" exception when calling Microsoft::Graphics::Canvas::Text::CanvasTextFormat::GetSystemFontFamilies();

**Comment by shawnhar** [comment] 2016-06-11 17:03
@jyoungl6, same reply as to previous people who reported this: please share a project that reproduces your issue.

**Comment by jyoungl6** [comment] 2016-06-11 17:08
@shawnhar I was getting ready to put together a sample project but now by some miracle my x86 version is working and I can't reproduce the problem! The only thing I did prior to this success was that I built, deployed and ran (successfully) the ARM version.

**Comment by Ponant** [comment] 2017-04-04 15:02
I got the reverse issue of @jyoungl6 , namely it crashed with x64 but worked with x86. I am using it to save ink from UWP InkCanvas into PNG images. I installed the NuGet package to a UWP anniversary build app and added this method taken from the MS Coloring Book sample.

   ```
CanvasDevice device = CanvasDevice.GetSharedDevice();

            using (var renderTarget = new CanvasRenderTarget(device, (float)inkCanvas.ActualWidth, (float)inkCanvas.ActualHeight, 96f))
            {
                using (CanvasDrawingSession ds = renderTarget.CreateDrawingSession())
                {
                    ds.Clear(Colors.White);

                    ds.DrawInk(inkCanvas.InkPresenter.StrokeContainer.GetStrokes());
                }

                await renderTarget.SaveAsync(stream, CanvasBitmapFileFormat.Png);
            }
```
Let me know if you need more info.

**Comment by Ponant** [comment] 2017-04-04 17:30
I deleted the bin and obj folder and now it works with x64.
