### ISSUE TITLE
VS designer not rendering CanvasControl?

### ISSUE THREAD

**Issue by saukun** [Microsoft/Win2D#558] opened 2017-09-15 20:23 UTC
Hi,

Just created blank UWP app. Referenced latest Win2D nugget 1.21.
In MainPage.xaml added

       <xaml:CanvasControl x:Name="canvas"/>

In MainPage.cs

        public MainPage()
        {
            this.InitializeComponent();
            canvas.Draw += Canvas_Draw;
        }
        private void Canvas_Draw(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasDrawEventArgs args)
        {
            var brush = new CanvasLinearGradientBrush(sender, new CanvasGradientStop[2] { new CanvasGradientStop() { Position = 0f, Color = Colors.Red }, new CanvasGradientStop() { Position = 1f, Color = Colors.Black } })
            {
                StartPoint = new System.Numerics.Vector2(0f, 0f),
                EndPoint = new System.Numerics.Vector2(0f, 200f)
            };
            args.DrawingSession.FillRectangle(0f, 0f, 200f, 200f, brush);
        }

Compiled. VS designer is white. If I run application - gradient rectangle IS displayed. Is this by design, VS designer bug or I'm missing something? 

Thanks,
Saulius

**Comment by shawnhar** [comment] 2017-09-15 20:33
The designer just renders controls without the full application logic, so event handlers like CanvasControl.Draw are not invoked in this environment.  Therefore, you just see the clear color of your CanvasControl but not whatever custom rendering your app may be doing onto it.

If you package up your drawing code to create a new control of your own (see for example the glow control in Example Gallery) then that will show in the designer.

**Comment by saukun** [comment] 2017-09-16 13:46
Sorry, I oversimplified my sample.

So if my user control would look like this

    public sealed partial class MyControl : UserControl
    {
        private CanvasControl canvas;

        public MyControl()
        {
            this.InitializeComponent();

            this.Loaded += MyControl_Loaded;
            this.Unloaded += MyControl_Unloaded;
        }

        private void MyControl_Unloaded(object sender, RoutedEventArgs e)
        {
            canvas.RemoveFromVisualTree();
            canvas = null;
        }

        private void MyControl_Loaded(object sender, RoutedEventArgs e)
        {
            canvas = new CanvasControl();
            canvas.Draw += Canvas_Draw;
            Content = canvas;
        }

        private static void Canvas_Draw(CanvasControl sender, CanvasDrawEventArgs args)
        {
            var stops = new CanvasGradientStop[2];
            stops[0].Position = 0;
            stops[0].Color = Color.FromArgb(255, 255, 0, 0);
            stops[1].Position = 1;
            stops[1].Color = Color.FromArgb(255, 0, 0, 0);

            var brush = new CanvasLinearGradientBrush(sender, stops);

            //brush.StartPoint = new System.Numerics.Vector2(0, 0);
            //brush.EndPoint = new System.Numerics.Vector2(50, 50);

            args.DrawingSession.FillRectangle(0f, 0f, 50f, 50f, brush);
        }
    }

I would see some red/black rectangle. But if only I uncomment brush.StartPoint/ brush.EndPoint lines I see nothing in VS designer, but it's rendered as expected in runtime.

Thanks,
Saulius

**Comment by shawnhar** [comment] 2017-09-17 16:07
Can you share a repro app that shows this problem please?

**Comment by saukun** [comment] 2017-09-18 08:23
[CanvasControl_Vector2_Problem.zip](https://github.com/Microsoft/Win2D/files/1310048/CanvasControl_Vector2_Problem.zip)

**Comment by shawnhar** [comment] 2017-09-18 20:31
Thanks for the repro.  This appears to be a designer bug, caused by the designer being unable to resolve CoreCLR types such as System.Numerics.Vector2.

According to https://blogs.msdn.microsoft.com/visualstudio/2017/09/11/a-significant-update-to-the-xaml-designer, this problem is fixed in the preview release of the designer when targeting Windows 10 Fall Creators Update.

**Comment by shawnhar** [comment] 2018-02-05 16:39
I'm closing this issue as the Fall Creators Update is now officially released.

**Closed by shawnhar** 2018-02-05 16:39 UTC
Labels: bug, external
