### ISSUE TITLE
Bitmap pixel format is not supported.

### ISSUE THREAD

**Issue by Dylan-H** [Microsoft/Win2D#255] opened 2016-02-01 13:11 UTC
`	auto resb = Concurrency::create_task(BitmapDecoder->GetSoftwareBitmapAsync());
		resb.then([g,bbox](SoftwareBitmap^ bmp)
		{
			
BitmapPixelFormat bpf = bmp->BitmapPixelFormat; //bpf  is BitmapPixelFormat.Bgra8
			CanvasBitmap^ cbmp = CanvasBitmap::CreateFromSoftwareBitmap(g, bmp); // error format not  support
			     g->DrawImage(cbmp, bbox,Rect(0, 0, cbmp->SizeInPixels.Width,         cbmp->SizeInPixels.Height));
			}
		},Concurrency::task_continuation_context::use_current());`

**Comment by shawnhar** [comment] 2016-02-01 14:39
What pixel formats are supported by Win2D is documented here:

http://microsoft.github.io/Win2D/html/PixelFormats.htm

**Comment by shawnhar** [comment] 2016-02-01 14:43
In this case the issue is likely with the alpha mode of your software bitmap.

**Comment by Dylan-H** [comment] 2016-02-01 15:04
@shawnhar How can I change the appha mode of softwarebitmap

**Comment by Dylan-H** [comment] 2016-02-01 15:12
@shawnhar  the alpha mode is BitmapAlphaMode::Straight

**Comment by shawnhar** [comment] 2016-02-01 15:26
SoftwareBitmap is outside my area of expertise, but looking at its docs, seems it has a Convert method that can change its format.

**Comment by Dylan-H** [comment] 2016-02-01 15:41
@shawnhar I have changed the alpha mode to  Premultiplied , and I can get the CanvasBitmap,
but now the  g->DrawImage(cbmp)  is not anything be painted.

**Comment by Dylan-H** [comment] 2016-02-01 15:47
@shawnhar    throw excption :      The object is closed

**Comment by shawnhar** [comment] 2016-02-01 17:28
You are not giving anywhere near enough information for me to understand what you are doing wrong.  You need to show both what your code is, and explain how this fails.  (somehow it both paints nothing, but also throws an exception?)

**Comment by shawnhar** [comment] 2016-02-08 15:16
Closing issue as it has been a week and the requested information has not been provided.

Feel free to reactivate if you are able to provide a simple repro app or detailed explanation of what you are doing and where that is failing.

**Closed by shawnhar** 2016-02-08 15:16 UTC
Labels: need info, question
