### ISSUE TITLE
Tab symbols have wrong width when they are replaced by custom TextInline objects

### ISSUE THREAD

**Issue by misupov** [Microsoft/Win2D#217] opened 2015-12-30 19:25 UTC
In my custom text editor control I would like to show punctuation symbols (spaces, tabs, etc.) like it is done in MS Word and other text editors (i.e. dots for spaces and arrows for tabs).
For this purpose I'm currently using my own implementation of ICanvasTextInlineObject which draws visual symbols for punctuation marks. Everything works fine for "space" character, but when I replace "tab" chars with my TabGlyph, I expect that glyphs following after tab symbol will be shifted by DrawBounds.Width of TabGlyph. In fact, the width of custom Inline objects seems to be ignored for tab symbols.

Here is how I replace tab chars with custom TabGlyph's:
```csharp
for (int index = 0; index < s.Length; index++)
{
  if (s[index] == '\t')
  {
    textLayout.SetInlineObject(index, 1, new TabGlyph(drawingSession));
  }
}
```

And here is the implementation of TabGlyph:
```csharp
private class TabGlyph : ICanvasTextInlineObject
{
  private const float WIDTH = 100;  // For issue demonstration only
  private const float HEIGHT = 20;  // For issue demonstration only

  private readonly CanvasDrawingSession _drawingSession;

  public TabGlyph(CanvasDrawingSession drawingSession)
  {
    _drawingSession = drawingSession;
  }

  public void Draw(ICanvasTextRenderer textRenderer, Vector2 point, bool isSideways, bool isRightToLeft, object brush)
  {
    _drawingSession.DrawRectangle(
      new Rect(point.X, point.Y, WIDTH, HEIGHT),
      Colors.Red);
    }

  public float Baseline => (float) -Size.Height;
  public CanvasLineBreakCondition BreakAfter => CanvasLineBreakCondition.Neutral;
  public CanvasLineBreakCondition BreakBefore => CanvasLineBreakCondition.Neutral;
  public Rect DrawBounds => new Rect(0, 0, WIDTH, HEIGHT);
  public Size Size => new Size(WIDTH, HEIGHT);
  public bool SupportsSideways => false;
}
```

**Comment by damyanp** [comment] 2015-12-30 21:01
I've experimented with this a bit, and to be clear - if you replace any character other than tab with TabGlyph then it works as expected.

Tabs are somewhat special in that their width depends on where they've ended up in the layout.  For example, if I set the string to "A\tB\nAA\tB" then I get something that looks like:

    A        B
    AA       B

So the tab on the first line is wider than the tab on the second line.

I'm guessing that this is what is causing the unexpected interaction between the inline object and the tabs.  I'll dig further (but probably won't be able to get an answer to this until the new year).

In the meantime, I'd suggest modifying your string to replace the tabs with some other character.  However, I do wonder if this is what you really want to do since a fixed width tab isn't probably not what you have in mind.

I wonder if this is more like what you need to do:

    for (int index = 0; index < s.Length; index++)
    {
        if (s[index] == '\t')
        {
            var region = textLayout.GetCharacterRegions(index, 1);
            drawingSession.DrawRectangle(region[0].LayoutBounds, Colors.Red);
        }
    }

**Comment by misupov** [comment] 2015-12-30 21:47
Thanks, Damyan! I think your approach with GetCharacterRegions is more appropriate than creating custom objects.

**Comment by damyanp** [comment] 2016-01-05 20:27
I've confirmed that this behavior with tabs and inline objects is an expected behavior of DWrite.

I'm closing this issue now, but feel free to reopen if necessary.

**Closed by damyanp** 2016-01-05 20:27 UTC
