### ISSUE TITLE
Crash in Windows Store

### ISSUE THREAD

**Issue by SebastianStehle** [Microsoft/Win2D#168] opened 2015-10-01 10:54 UTC
Hi, I published a new App to the AppStore just some hours ago. Everything works fine on my machine but I see the following exceptions in Application Insights:

System.MissingMethodException
Method not found: 'Void Microsoft.Graphics.Canvas.CanvasDrawingSession.put_Transform(System.Numerics.Matrix3x2)'.

I also noticed that Resharper shows a lot of errors like this: ﻿

Cannot convert source type 'System.Numerics.Matrix3x2' to target type 'Windows.Foundation.Numerics.Matrix3x2'

I ignored them so far, because it compiles and works, but I wonder if there might be some issue.

**Comment by shawnhar** [comment] 2015-10-01 14:42
I am not familiar with Application Insights.  Can you explain how to repro this issue?

The Resharper bug is fixed in the R# 10 EAP2 builds.

**Comment by SebastianStehle** [comment] 2015-10-01 15:02
The problem is: I cant reproduce the issue, I just see the exception logs in Application Insights :(

The stack trace is quite short, so I dont have any helpful information :(

**Comment by shawnhar** [comment] 2015-10-01 15:09
That callstack is almost certainly a red herring.  I suspect you are crashing somewhere unrelated, but this tool doesn't understand the WinRT projection of numerics types so it gets confused while trying to process the callstack.

**Comment by SebastianStehle** [comment] 2015-10-01 15:37
Maybe, but the exception message is very specific and accurate I think ;)

**Comment by shawnhar** [comment] 2015-10-01 16:45
The exception message is specific, but (like the Resharper errors which have a similar root cause) not really a problem in your code.

This indicates that someone is trying to reflect over or JIT your assembly using a CLR runtime or bytecode reader that doesn't understand the WinRT projection of System.Numerics -> Windows.Foundation.Numerics.  So they look for methods using the non-projected version of these types, don't find it, and blow up.

(Resharper fixed this in R# 10 EAP2 by adding knowledge of these projected types to their IL parser)

This won't happen at runtime while your app executes, because that is using CoreCLR which properly understands the projection.  So I'm pretty confident this is a tooling bug - my guess is they're trying to gather extra data about some unrelated crash (we have no way to know what that was), and along the way are attempting reflection using a wrong CLR version, so what you're seeing is the callstack when that reflection fails.

**Comment by shawnhar** [comment] 2015-10-01 17:53
Sebastian, could you please share a full stack trace from this exception?

**Comment by SebastianStehle** [comment] 2015-10-01 19:04
Sure:

System.MissingMethodException
Method not found: 'Void Microsoft.Graphics.Canvas.CanvasDrawingSession.put_Transform(System.Numerics.Matrix3x2)'.
   at Hercules.Model.Rendering.Win2D.Win2DRenderer.Render(CanvasDrawingSession session)
   at Hercules.Model.Rendering.Win2D.Win2DRenderer.Canvas_Draw(Object sender, CanvasDrawEventArgs args)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Hercules.App.Controls.CanvasControlWrapper.OnDraw(CanvasDrawEventArgs e)
   at Hercules.App.Controls.CanvasControlWrapper.<.ctor>b__13_1(CanvasControl sender, CanvasDrawEventArgs args)

The relevant code is here:
https://gist.github.com/SebastianStehle/4e04c78102849cc4763a

**Comment by shawnhar** [comment] 2015-10-01 20:58
Thanks.

What kind of app are you building?  What project template does it use, what .NET framework version, and do you have .NET Native turned on?

thx

**Comment by SebastianStehle** [comment] 2015-10-01 21:37
It is a Windows Universal App, Minimum Version: Windows 10, Build 10240, it is a normal Template and .NET Native is turned on.

**Comment by shawnhar** [comment] 2015-10-02 05:02
Update:  I'm in contact with some experts from .NET Native and Application Insights teams, but they have no idea what could be causing this.

Double checking - you have never seen the crash locally?   Any ability to extract more information about it?  (a crash dump would be awesome, or any clues from patterns about what type of machines it occurs on etc)

**Comment by SebastianStehle** [comment] 2015-10-02 09:44
I never had the problem on my machine. I just found out that all this exceptions happen in Redmond ;) ... perhaps it might be some server testing the apps in the publishing process?

Continent
North America
	
Country or region
United States
	
State or province
Washington
	
City
Redmond

**Comment by shawnhar** [comment] 2015-10-02 12:35
Oooh, now THAT is an interesting clue indeed!

Is there a timeline to these exceptions?   All happened shortly after submitting and then none since, for instance?  :-)

(if they are still happening, that would point in a different direction)

**Comment by SebastianStehle** [comment] 2015-10-02 14:11
The app is brand new and there are almost no downloads, but there are no exceptions anymore for the last 24hours, so it might be the publishing process.

**Comment by shawnhar** [comment] 2015-10-03 17:08
Very interesting!  It definitely does look like this is something unusual about the store cert process.  I've passed this info along to the store team.

I'm going to close this issue as there does not appear to be a Win2D bug here, and the exceptions seem benign (not causing store cert failures).  Please reactivate if you see any more serious problems (store rejections, or crashes coming from places other than store cert).

**Closed by shawnhar** 2015-10-03 17:08 UTC
