### ISSUE TITLE
DrawingSessions for CanvasImageSource and CanvasVirtualImageSource apply the wrong offset when UnitMode=Pixels

### ISSUE THREAD

**Issue by FabricioCabeca** [Microsoft/Win2D#160] opened 2015-09-18 19:12 UTC
Hi, I've been playing with VirtualCanvasControl as a substitute to the CanvasControl so I can use the region invalidate. When using dips it seems to work as expected, but using pixels it may render the wrong source position. Please notice it is not a wrong conversion on my side, when invalidating the whole area everything is drawn where expected.
```
foreach (var region in args.InvalidatedRegions)
{
using (var ds = sender.CreateDrawingSession(region))
{
ds.Units = CanvasUnits.Pixels;
i++;
i %= 100;
ds.FillCircle(50 + i, 50, 50, Windows.UI.Colors.Red);
ds.Dispose();
//sender.Invalidate();
sender.Invalidate(new Rect(0, 0, 200, 200));
}
}
```
CanvasUnits.Pixels + sender.Invalidate() works
CanvasUnits.Dips + sender.Invalidate(Rect) works
CanvasUnits.Pixels + sender.Invalidate(Rect) does not work as expected

Tested with 1.4.0

Thanks

**Comment by shawnhar** [comment] 2015-09-18 19:15
This is expected, because the CanvasDrawingSession.Units property only affects the specific CanvasDrawingSession that it was set on  (if you have multiple drawing sessions, it's entirely valid to have different Units on each one).

Invalidate is a method of CanvasVirtualControl, not CanvasDrawingSession, so it is not affected by the drawing session units.

Invalidate always operates in dips.

**Comment by damyanp** [comment] 2015-09-18 19:16
Note that you can use [ConvertPixelsToDips](http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_UI_Xaml_CanvasVirtualControl_ConvertPixelsToDips.htm) to convert your pixel values to dips suitable for passing to Invalidate.

**Comment by FabricioCabeca** [comment] 2015-09-18 19:36
Thanks for the quick feedback. I do set the Units at every drawing operation, as in the example above. The Rect used does contain the circle drown with both Units, so it is expected to see the same motion, but with pixels it sometimes draws the circle beginning outside(!) the canvas, you may try the example above, it is easier to understand what is going on.

**Comment by damyanp** [comment] 2015-09-18 19:42
Could you put a complete example up somewhere?  For example, it's not clear from the code above exactly what's happening with the 'i' variable.  A complete sample would unambiguously allow us to reproduce the problem.

**Comment by FabricioCabeca** [comment] 2015-09-18 19:44
'i' is a global with initial value 0. I can't send a complete sample right now but it is almost the code above.

**Comment by damyanp** [comment] 2015-09-18 19:58
I think we have an idea about what might be going on here - don't worry about the full example.  We'll track getting a fix for this.

(When CanvasVirtualImageSource renders to the underlying XAML SurfaceImageSource we need to apply an offset. We do this by modifying the transform.  Currently, this doesn't take into account the unit mode.)

Thanks for reporting this issue!

**Comment by FabricioCabeca** [comment] 2015-09-18 20:03
You're welcome !

Good job with Win2D btw, I'm having a great time with it  :-)

**Closed** 2015-10-12 19:14 UTC
Labels: bug
