### ISSUE TITLE
WINMDEXP : error WME1007: Could not resolve reference 'Assembly(Name=Windows.Foundation.FoundationContract (Visual Studio bug)

### ISSUE THREAD

**Issue by t-sch** [Microsoft/Win2D#299] opened 2016-03-09 09:48 UTC
Hi,
after upgrading my solution to use 1.15.0 (or 1.16.0) my project doesn't build any more. I get the error message

_WINMDEXP : error WME1007: Could not resolve reference 'Assembly(Name=Windows.Foundation.FoundationContract, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null)'._

When going back to 1.14.0 I can build again.

Any ideas?

-Thomas

**Comment by shawnhar** [comment] 2016-03-09 15:54
Please share a (ideally simplified) repro project so we can take a look.

**Comment by t-sch** [comment] 2016-03-10 11:24
Easier said than done.

I have a solution with a number of projects, C++ legacy code, C++ Runtime Components wrapping these, a C# Runtime Component that works as a UserControl and references them, and a UWP app that uses this control. The build problem is independent of the target/min version of my UserControl, I tried both 10240 and 10586.

I created an empty project (c# Runtime Component) in a fresh solution with the same references, Nuget and local. Compiles fine.
Then I even included my two referenced projects (C++ Runtime Components) and changed the winmd refs to project refs. Builds.

I compared the csproj files and found no significant diffs.

When I looked into the first version of the csproj file with winmd references (new solution) I observed strong names with the obscure 255.255.255.255 version in the references to my winmds. But that solution did build, so I don't know if it is of importance.

What should I do now?

**Comment by shawnhar** [comment] 2016-03-10 12:36
Afraid you are going to have to either find a way to get us a repro, or solve the problem on your own.

If you are able to create a new project that does build correctly, you could just switch over to that?  Or diff it vs. the one with problems to understand where things went wrong.

**Comment by shawnhar** [comment] 2016-03-17 21:06
I'm closing this issue, as it is not actionable without some way for the Win2D team to repro the problem you are seeing.

Feel free to reactivate if you're able to get us a repro.

Thanks!

**Comment by reneherrero** [comment] 2016-04-26 23:14
Hey guys,

Same is happening here.  1.14 is good, but 15, 16 and 17 all have the same symptoms.  Here's the error:
WINMDEXP : error WME1007: Could not resolve reference 'Assembly(Name=Windows.Foundation.FoundationContract, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null)'.

Here's a project that reproduces the error: (just one interface, so as simple as it gets!)
https://github.com/reneherrero/Win2DBug

Hope it helps,

Rene

**Comment by damyanp** [comment] 2016-04-26 23:36
Thank you for the good repro here.  I can see the same issue locally.

**Comment by reneherrero** [comment] 2016-04-27 02:57
Cool.  Glad it helped.

Note that this doesn't happen in C++, only C#.

**Comment by shawnhar** [comment] 2016-05-16 22:33
Hi, wanted to share a quick update on this issue:

We've root caused this to a bug in the winmdexp.exe tool, which is part of the SDK used to build Win2D.

Still working through the details of when we'll be able to release an updated version of winmdexp, or whether there is any way Win2D can work around the issue in the meantime.

**Comment by reneherrero** [comment] 2016-05-17 15:31
Something tells me this was a tough one to root cause...  thanks for that.

**Comment by shawnhar** [comment] 2016-08-19 21:17
I just confirmed that this bug is fixed in the 4.6.2 SDK version of winmdexp.exe.

Unfortunately, Visual Studio 2015 Update 3 is still using the 4.6.1 SDK when building UWP projects, but you can explicitly select the 4.6.2 version of this tool by editing your .csproj and adding, inside the <PropertyGroup> element near the top of the file:

    <WinMdExpToolPath>$(FrameworkSDKRoot)\bin\NETFX 4.6.2 Tools</WinMdExpToolPath>

**Comment by shawnhar** [comment] 2016-08-21 16:05
This will be fixed in the next major version of Visual Studio (codenamed "dev15").

Until that is available, the above WinMdExpToolPath workaround can be used with Visual Studio 2015 Update 3.

**Comment by t-sch** [comment] 2016-08-22 09:00
Thanks, the workaround helps for now.

**Comment by shawnhar** [comment] 2017-05-26 22:07
This issue is fixed in Visual Studio 2017.

**Closed by shawnhar** 2017-05-26 22:07 UTC
Labels: bug, external
