### ISSUE TITLE
Store issue with "API 13"

### ISSUE THREAD

**Issue by deltakosh** [Microsoft/Win2D#141] opened 2015-08-25 20:51 UTC
When creating an UWP with Win2D 1.2.0, the store certification process fails with this error:
![capture](https://cloud.githubusercontent.com/assets/1306056/9479054/6774083c-4b30-11e5-9bb7-4268999fe276.JPG)

**Comment by shawnhar** [comment] 2015-08-25 20:57
Thanks for the report.  This was reported on the blog recently (http://blogs.msdn.com/b/win2d/archive/2015/08/17/win2d-1-2-0-gradient-meshes-and-virtual-image-sources.aspx) and I already started an internal conversation with the Store team to figure out what is going wrong.

Let's use this issue to track progress on that - I'll update here as soon as I have some info and ETA for a fix.

As a temporary workaround, Win2D 1.1.0 will not suffer from this issue.  The problem is that Store is (incorrectly) rejecting one of the new gradient mesh APIs that we added in 1.2.0.

**Comment by deltakosh** [comment] 2015-08-25 21:14
Yep using 1.1 works perfectly well :)

**Comment by shawnhar** [comment] 2015-08-25 21:24
Store team understands the problem - now working on a solution.

**Comment by shawnhar** [comment] 2015-08-26 00:32
Update: Store team is able to issue waivers to apps that hit this problem while they are working a permanent fix.

If you hit this problem, please share the ID of your title so we can get this set up.  This is the Package/Identity/Name, Package/Identity/Publisher, and Package/Properties/PublisherDisplayName information displayed under App identity in the Windows dev center.

**Comment by deltakosh** [comment] 2015-08-26 00:44
here is mine:
* 15798DavidCatuhe.UrzaGatherer
* CN=A497AE31-0484-435B-8E45-4491C81DB665
* David Catuhe

Thank you very much!

**Comment by shawnhar** [comment] 2015-08-27 17:01
deltakoshand and LMK - we've put a temporary waiver in place for your apps so they will go through in spite of this issue if you resubmit.

Actively working on a proper permanent fix.

Apologies for the inconvenience!

**Comment by deltakosh** [comment] 2015-08-27 17:49
It worked I was able to submit my app and have it validated:) Thanks a lot!

**Comment by alexeygritsenko** [comment] 2015-08-28 15:42
Hi, I have the same problem (
Name: АйДаПрикол :)
Application ID 9NBLGGH0K2PM
![ashampoo_snap_2015 08 28_18h40m26s_001_](https://cloud.githubusercontent.com/assets/10233486/9550513/7e458118-4db4-11e5-82b0-cc4eb70a4f72.png)

**Comment by damyanp** [comment] 2015-08-28 18:00
@alexeygritsenko - can you try resubmitting please?  I've been told that the permanent fix has been deployed now.

**Comment by alexeygritsenko** [comment] 2015-08-29 04:04
@damyanp ok, I resubmitting app. Certification = done! Thanks!

**Comment by shawnhar** [comment] 2015-08-31 14:14
This issue is fixed in the store cert process now.

**Closed** 2015-08-31 14:14 UTC
Labels: bug
