### ISSUE TITLE
MediaCapture with GPU-based IBasicVideoEffect regression in Win10 Anniversary Update (OS bug)

### ISSUE THREAD

**Issue by riseupgames** [Microsoft/Win2D#397] opened 2016-07-30 23:47 UTC
Hello,

The issue (reported here: https://github.com/Microsoft/Win2D/issues/350) is marked closed, but I am experiencing it on both 10.0.14372.0 (Lumia 640XL) and 10.0.14393.0 (Lumia 950XL).

Thank you!

**Comment by shawnhar** [comment] 2016-08-01 15:58
This is due to a regression in the OS MediaCapture implementation.  Unfortunately there is no way to work around the issue from the Win2D side, so we must wait for a fix in the OS.  The problem is understood and right teams are working on it - I will update here when we have info about when the fix will be available.

(for my reference, this is internal bug #7956512)

**Comment by riseupgames** [comment] 2016-08-01 17:26
Thank you for the quick reply! Hoping a fix can come soon, have an app ready to publish.

**Comment by shawnhar** [comment] 2016-08-04 14:35
Quick update: the fix for this issue is implemented and checked in to internal OS builds - we're now working through the servicing process to get it released externally.  Afraid I don't have a good idea how long this will take, but it's on the way.

**Comment by riseupgames** [comment] 2016-08-04 23:53
Glad to hear it, thank you!

**Comment by shawnhar** [comment] 2016-09-06 15:08
This fix is in build 14393.103, which was sent out as a Release Preview on 8/25  (http://www.windowscentral.com/windows-10-build-14393103-release-preview)

**Closed** 2016-09-06 15:08 UTC
Labels: bug, external
