### ISSUE TITLE
Joining two line

### ISSUE THREAD

**Issue by ratishphilip** [microsoft/Win2D#775] opened 2020-06-12 17:27 UTC
I am trying to render a gradient along a path. I implemented the `ICanvasPathReceiver` interface to split the given path into smaller lines and then I render these lines using the calculated gradient brush. 
So far so good.
The only problem seems to be with the joining of the two lines and calculating the miter and how to render it properly with a gradient.

![image](https://user-images.githubusercontent.com/7021835/84529560-82567f00-ac96-11ea-8022-30a3184d1dd5.png)

![image](https://user-images.githubusercontent.com/7021835/84529582-8aaeba00-ac96-11ea-9f44-238225ae489a.png)

I am trying to achieve something like this

![image](https://user-images.githubusercontent.com/7021835/84529671-b467e100-ac96-11ea-8d12-26bc4cf9a81c.png)

But I am able to get till this point

![image](https://user-images.githubusercontent.com/7021835/84529985-3a842780-ac97-11ea-927a-984f18c48121.png)

Does Win2d provide any way to achieve this?

**Comment by clandrew** [comment] 2020-06-12 17:34
The thing you're looking for is path gradients. Unfortunately Direct2D which Win2D is built on top of doesn't have this feature. I think everyone can agree path gradients look cool in simple cases but the problem is they're extremely hard to formally specify in all cases, and hard to robustly get right. 

GDI+ does have them
https://docs.microsoft.com/en-us/windows/win32/gdiplus/-gdiplus-creating-a-path-gradient-use

so one option might be to draw some of your scene with with GDI+, if that is an option for you, and inter-operate it with your other graphics.

**Comment by damyanp** [comment] 2020-06-12 17:39
Is this something that gradient meshes can help with at all?

**Comment by ratishphilip** [comment] 2020-06-12 17:57
> The thing you're looking for is path gradients. Unfortunately Direct2D which Win2D is built on top of doesn't have this feature.
> 
> GDI+ does have them

I thought Direct2D would have this feature as it is more advanced compared to GDI+.

**Comment by ratishphilip** [comment] 2020-06-12 18:07
Once I split the path into multiple lines the line join goes awry.

This is how the path is rendered with a solid color

![image](https://user-images.githubusercontent.com/7021835/84533172-6e158080-ac9c-11ea-989e-02d26c2dfa25.png)

When I split them into lines using ICanvasPathReceiver, I get this

![image](https://user-images.githubusercontent.com/7021835/84533395-e8de9b80-ac9c-11ea-9aa0-0f6ccac0c2ea.png)

**Comment by clandrew** [comment] 2020-06-12 18:27
Unfortunately it's not really a question of 'basic' versus 'advanced', it's a question of do you want 1) lots of features but some of them are flimsy and only work 50% of the time or 2) fewer but very robust features.

Re: damyanp's comment about gradient mesh- yeah gradient mesh would help for some simple cases, just not all of them, so it depends on what you're drawing. For example, self-intersecting paths. If you want a "painter's algorithm" type look, then a long skinny gradient mesh whose edge points are the flattened, widened path points might work. If you don't though then you're on your own.

Re: the above diagram It looks like you are putting paths with flattening through a path receiver and then calling DrawLine on each flattened segment. This wouldn't allow for any line joins. If you want to preserve joins you need to do it differently. For example, you could widen the geometry, tessellate the result and then fill the triangles as you choose (e.g., with a linear gradient).

**Comment by ratishphilip** [comment] 2020-06-12 18:49
>  If you want to preserve joins you need to do it differently. For example, you could widen the geometry, tessellate the result and then fill the triangles as you choose (e.g., with a linear gradient).

This seems a good idea.

Here is how the tesselated stroked path looks

![image](https://user-images.githubusercontent.com/7021835/84536483-ca7b9e80-aca2-11ea-99a9-25f428073422.png)

Now I need to calculate the correct gradient for each triangle (or should I use GradientMesh?)

**Comment by shawnhar** [comment] 2020-08-13 17:58
I'm going to close this issue out as the conversation didn't end up indicating a Win2D bug.

**Closed by shawnhar** 2020-08-13 17:58 UTC
