### ISSUE TITLE
Class not registered when running app with Windows Phone 8.1 Emulator

### ISSUE THREAD

**Issue by kylefowler** [Microsoft/Win2D#66] opened 2015-04-30 07:22 UTC
I'm trying to use CanvasBitmap and CanvasCommandList and any time I try and create a new one, I get class not registered exceptions. This is in a Windows Phone 8.1 Store app, attempting to run with x86 in the emulator.

An exception of type 'System.TypeLoadException' occurred in APPNAME.exe but was not handled in user code

Additional information: Requested Windows Runtime type 'Microsoft.Graphics.Canvas.CanvasBitmap' is not registered.

**Comment by clandrew** [comment] 2015-04-30 11:38
Thanks for bringing this issue to our attention. We have unit tests which run on the phone emulator and verify basic functionality, and these unit tests continue to pass, so that implies there is something different about this project or environment to cause this. 

Could you specify
* What version of VS you're using
* How you are consuming Win2D (if by NuGet package, which one)
* Which build config (debug or release)

I can see if it reproes on our end.

**Comment by kylefowler** [comment] 2015-04-30 14:38
Using Visual Studio Ultimate 2013 (12.0.31101.00 update 4).

I;ve got the nuget package version 0.0.17 and am attempting to use it in a debug phone project (windows runtime).

**Comment by clandrew** [comment] 2015-04-30 18:44
I made phone projects in debug, with package version 0.0.17, on each of update 3 and update 4, and made the project instantiate each of CanvasBitmap and CanvasCommandList. Compiles and runs with no class registration error. 

Could you say exactly which template your app is based on? Maybe there is some key difference here. Or better yet, send the project itself?

It would be very helpful to check it out in person! Unfortunately I'm at the Redmond campus and not at Build. Hope you're enjoying the conference.

**Comment by kylefowler** [comment] 2015-04-30 19:44
Unfortunately I cant share the project, maybe i can make a new one. It also doesnt work on the phone either, so not limited to the emulator. I'll keep poking.

**Comment by clandrew** [comment] 2015-04-30 19:57
Ok, thanks for the update.

**Comment by ankohanse** [comment] 2015-05-02 09:42
Sounds like a duplicate of my issue #59. I can confirm that one was resolved with v 0.0.17.

**Comment by shawnhar** [comment] 2015-05-04 16:32
This does sound like the same thing as issue #59, so I'm going to close it out.  Please reactivate if you still see the problem using Win2D 0.0.17 with VS 2013 Update 5, and are able to provide a repro.

**Closed by shawnhar** 2015-05-04 16:32 UTC

**Comment by kylefowler** [comment] 2015-05-04 17:23
I dont think its the same issue. Ive updated to Update 5 and now it throws me a different error at the same code.

+		[System.NotImplementedException]	{System.NotImplementedException: The method or operation is not implemented.

```
               using (var device = new CanvasDevice())
                {
                    var bmp = await CanvasBitmap.LoadAsync(device, new Uri(_image.StorageFile.Path)); // throws here
                    var renderTarget = new CanvasRenderTarget(device, (float)bmp.SizeInPixels.Width, (float)bmp.SizeInPixels.Height, 96);
}
```

**Comment by shawnhar** [comment] 2015-05-04 17:27
Could you try calling RandomAccessStreamReference.CreateFromUri on the same URI you are passing to CanvasBitmap.LoadAsync?

**Comment by kylefowler** [comment] 2015-05-04 17:34
Ok, looks like if I change to load the IRandomAccessStream from the StorageFile and then use the stream in LoadAsync it does not crash. It writes blank images but at least it doesnt crash.
