### ISSUE TITLE
Cannot create instance of type 'Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl'

### ISSUE THREAD

**Issue by Foxsterc** [Microsoft/Win2D#452] opened 2016-11-01 12:35 UTC
Hi,

If I run the sample "SimpleSample.uap" I get the error. This is using version 1.19. **Version 1.18 works!**

An exception of type 'Windows.UI.Xaml.Markup.XamlParseException' occurred in SimpleSample.uap.exe but was not handled in user code

WinRT information: Cannot create instance of type 'Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl' [Line: 20 Position: 73]

Additional information: The text associated with this error code could not be found.

Cannot create instance of type 'Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl' [Line: 20 Position: 73]

If there is a handler for this exception, the program may be safely continued.

Visual Studio 2015 with Update 3
Windows 10 Pro
Target version: Windows 10 Build 10586
Min version: Windows 10 Build 10240

Whether the config is Win32, x86, x64, ARM it fails on all of them. 

Thanks,

Dale
[UAP.zip](https://github.com/Microsoft/Win2D/files/563871/UAP.zip)

**Comment by shawnhar** [comment] 2016-11-01 14:47
This kind of error is usually a sign of stale state in Visual Studio.  Try forcing a clean rebuild of the project.

Your attachment works fine for me, btw.   (but I note that it is using Win2D 1.18.0 - is that what you intended?)

**Comment by Foxsterc** [comment] 2016-11-01 15:11
Hi,

 

No, I tried doing cleans and it makes no difference. The project I sent works fine using 1.18 but when changing it to 1.19 it fails.

 

 



 

 



 

 



 

 

Incidentally, it renders this screen then the crash happens (1.19). 

 

 



 

Working version (1.18)

 



 

Thanks,

Dale

**Comment by shawnhar** [comment] 2016-11-01 15:24
Did you mean to include screenshots in that post?  I just see big gaps in the text.

Anyway - this project works fine if I upgrade it to Win2D 1.19.0 as well (I just did this via the VS NuGet UI).

Please share a project that actually reproduces the problem you are having.

**Comment by Foxsterc** [comment] 2016-11-01 16:20
I did, but seems to be having issues uploading them.

I have uninstalled, cleaned etc v1.18 works 1.19 doesn't

Attached is the project which fails.

[Uploading UAP.zip…]()

**Comment by shawnhar** [comment] 2016-11-09 20:48
Closing due to lack of repro steps.  Feel free to reactivate if you are able to find a way we can repro what you are seeing.

**Closed by shawnhar** 2016-11-09 20:48 UTC
Labels: need info
