### ISSUE TITLE
Graphics Diagnostics breaks all IBasicVideoEffect Effects

### ISSUE THREAD

**Issue by sdaly2324** [Microsoft/Win2D#191] opened 2015-11-20 21:25 UTC
Set a break point in ExampleVideoEffect.cs SetEncodingProperties or ProcessFrame.
Run from the debugger and you hit them just fine.

Now run from the Graphics Debugger and you will hit get SupportedEncodingProperties and Close but you never hit SetEncodingProperties or ProcessFrame and the video never displays.

**Comment by shawnhar** [comment] 2015-11-20 22:18
Thanks for the report.  Looks like there are two things going on here:

1) The graphics debugging tools do not support hardware accelerated video operations, so when debugging is active the app sees a GPU without any video processing caps.
2) IBasicVideoEffect does not appear to handle lack of GPU video processing very well.

I've reported this issue to the team that owns IBasicVideoEffect.

**Comment by shawnhar** [comment] 2015-11-20 22:20
For my future reference, this is internal MS bug 5517849.

**Comment by shawnhar** [comment] 2015-11-30 20:02
Apparently this is the intended behavior for IBasicVideoEffect - it can still run in environments where GPU video processing is not available, but will not provide a graphics device or make the frame data available as Direct3D surfaces.  This means that Win2D video effects will not work when there is no GPU video capability (as when graphics diagnostics is active).

Closing the issue as there does not appear to be any bug here - just a combination of things that are not supported.

**Closed by shawnhar** 2015-11-30 20:02 UTC
Labels: bug, external
