### ISSUE TITLE
Code analysis problem with Vector2

### ISSUE THREAD

**Issue by Hartigan** [Microsoft/Win2D#159] opened 2015-09-18 09:06 UTC
I'm unable to set the Scale property on ScaleEffect with enable Code Analysis. The same issue was descirebed in [Issue #145](https://github.com/Microsoft/Win2D/issues/145) , but I can't build project when CA is enabled.

[Errors description](https://gist.github.com/Hartigan/ae91f6b69ae33b931b7f)

**Comment by shawnhar** [comment] 2015-09-18 12:58
This looks like a Code Analysis bug.  I'm trying to track down the right team to hand it on to.

Thanks for the report!

**Comment by shawnhar** [comment] 2015-09-18 18:13
Confirmed this is an FXCop bug, and reported it to the FXCop team.

(for my own future reference, this is tracked by internal MS issue 146115)

**Comment by shawnhar** [comment] 2015-10-12 22:00
This will be fixed in a future version of Visual Studio.

**Comment by jimm98y** [comment] 2015-10-20 13:59
I am probably running to the same issue when attempting to compile UWP with NET Native enabled where I use the AddCubicBezier method that takes Vector2 as a parameter. Compilation fails with the following message:
C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(791,7): error : Internal compiler error: Type 'System.Numerics.Vector2' was referenced in method 'Nullable_A_System_Numerics_Vector2_V___Impl.StubClass.get_Value(__ComObject)', but was not found necessary by analysis.

Are there any workarounds?

**Comment by shawnhar** [comment] 2015-11-30 22:00
This is fixed in Visual Studio 2015 Update 1  (released today).

**Closed by shawnhar** 2015-11-30 22:00 UTC
Labels: bug, external
