### ISSUE TITLE
Lumia 950 XL (Windows 10) - Performance

### ISSUE THREAD

**Issue by BrianBergh** [Microsoft/Win2D#216] opened 2015-12-29 22:45 UTC
I'm an old fan of XNA, and i have developed a few games for Windows, and Windows Phone (7.5 and 8/8.1). I was sad to discover that XNA was being discontinued. Then I just came across Win2D, WOW, a new api (new to me) that seems just as easy to manage as XNA :) I decided to create a simple test project, a blank page with just a CanvasAnimatedControl, showing a simple text scroller. In the update method i update the position, and in the draw method i draw the text. Simple and straight forward.

However, i noticed that the performance (when using the canvas with default options) was kind of lagging. Every few seconds the FPS drops from 60fps to 45..then 30. After yet a few seconds it rises to 60 again. The text choops as a result looking very ugly. I've tried to set IsFixedTimeStep to false, i've tried to make the canvas smaller and i've also tried to use Pixels unit instead of DPI. When using pixles instead of DPI the scroller seems to run more smooth, but no matter what i do, the FPS seems to top at 60 fps. (even with IsFixedTimeStep="False"), and the really strange thing is, that when i set the ForceSoftwareRenderer="True" it seems to run even smoother!?

I have rebooted the device, still it lags.

Is this because of a bug in the Windows 10 Mobile (im running 10586.36), or is it a bug in the Win2D api? Or is this really the performance we can expect from a Lumia 950XL?

here's the code:
UWP (Blank project):

&lt;Page
    x:Class=&quot;win2dTest.MainPage&quot;
    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
    xmlns:local=&quot;using:win2dTest&quot;
    xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot;
    xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
    xmlns:canvas=&quot;using:Microsoft.Graphics.Canvas.UI.Xaml&quot;
    mc:Ignorable=&quot;d&quot;&gt;
    &lt;canvas:CanvasAnimatedControl Update=&quot;canvas_Update&quot;  Draw=&quot;canvas_Draw&quot; Loaded=&quot;canvas_Loaded&quot; ClearColor=&quot;Black&quot; Name=&quot;canvas&quot; CreateResources=&quot;canvas_CreateResources&quot; SizeChanged=&quot;canvas_SizeChanged&quot;  /&gt;
&lt;/Page&gt;
  public sealed partial class MainPage : Page
  {
    public MainPage()
    {
      this.InitializeComponent();
    }
    Vector2 scrollPos = new Vector2();
    float speed = 100f;
    float tw = 0;
    private void canvas_Update(Microsoft.Graphics.Canvas.UI.Xaml.ICanvasAnimatedControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedUpdateEventArgs args)
    {
      float elapsed = (float)args.Timing.ElapsedTime.TotalSeconds; // calc once, for speed.
      scrollPos.X -= (elapsed * speed);
      if (scrollPos.X < -scroller_layout.DrawBounds.Width)
      {
        scrollPos.X = tw;
      }
    }
    string about = "This is just a scrolling demo with a very long text to see how it works on Windows Phone (Lumia 950 XL).";
    CanvasTextFormat scroller_format = new CanvasTextFormat { FontSize = 100.0f, WordWrapping = CanvasWordWrapping.NoWrap };
    CanvasTextLayout scroller_layout = null;
    //FPSCounter fpsCounter = new FPSCounter();
    private void canvas_Draw(Microsoft.Graphics.Canvas.UI.Xaml.ICanvasAnimatedControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedDrawEventArgs args)
    {
      args.DrawingSession.Units = CanvasUnits.Pixels;
      args.DrawingSession.DrawTextLayout(scroller_layout, scrollPos, Colors.White);
      //fpsCounter.Draw(args.DrawingSession);
    }
    private void canvas_Loaded(object sender, RoutedEventArgs e)
    {
    }
    private void canvas_CreateResources(Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedControl sender, Microsoft.Graphics.Canvas.UI.CanvasCreateResourcesEventArgs args)
    {
      scroller_layout = new CanvasTextLayout(canvas, about, scroller_format, 0.0f, 0.0f);
      scrollPos = new Vector2((float)canvas.ActualWidth, ((float)canvas.ActualHeight / 2) - ((float)scroller_layout.DrawBounds.Height / 2));
      tw = (float)canvas.ActualWidth;
    }
    private void canvas_SizeChanged(object sender, SizeChangedEventArgs e)
    {
      tw = (float)canvas.ActualWidth;
    }
  }

**Comment by damyanp** [comment] 2015-12-30 19:40
You shouldn't expect to see framerates higher than 60fps on phone - presenting frames is always locked to the vertical refresh rate.

Anyway, I suspect the glitching is caused by drawing the text each frame.

Rasterizing text can sometimes have surprising performance characteristics - for example, it may sometimes need to reload font data on one frame, but not another.  I would not be surprised if it is aggressively dropping glyphs that haven't been used for a while, especially when using very large font sizes.

If you want to get more consistent frame-to-frame performance then I would suggest that you prerender the text to an offscreen CanvasRenderTarget.  You may need to use several if the text is wider than CanvasDevice.MaximumBitmapSizeInPixels.


If you're just interested in seeing what Win2D can do that I'd suggest that you install the [Example Gallery](https://www.microsoft.com/store/apps/9NBLGGGXWT9F) application on your phone.  You can also get the source to this app by cloning the [Win2D-Samples](https://github.com/Microsoft/Win2D-samples) repo.  This will let you run it from within Visual Studio and have the frame rate counter display visible.

**Comment by BrianBergh** [comment] 2015-12-30 20:05
Thanks for the reply. I was just trying to do something simple, as I've done a million times in XNA (for Windows Phone 8), I never had any performance glitches in XNA with the exact same approach.

If i wanted the text to glow (animated) as in the old style game "Alien Breed", then i would have to create some masked images etc. I just don't understand how writing a simple text scroller should make the frame rate drop from 60 to 45 then 30 every few seconds? Its not that complicated (under the hood), also, it's only on the phone (Lumia 950 XL with 8 2ghz cores, and a fine gpu) - on the desktop (with a slower 4 cored cpu, and an old gfx card it runs 100% smooth and without glitches at all).

I'm just trying to understand if it's the api or if it's the phone (os or hardware), as it's the brand new Microsoft Lumia flagship, which should be capable of doing a such simple text scroller with nothing fancy going on, without having to pre-render it?

Anyway, thanks for the reply. I'd wait a few month before i test again to see if a few OS updates may help solving the problem, as it might just be a problem with the OS, as Win10 for phone is extreme (as in EXTREME) buggy :(

**Comment by damyanp** [comment] 2015-12-30 20:33
On XNA you were most likely drawing the text using a SpriteFont - where all the work to translate the font data into rasterized glyphs happens offline before the app runs.

In Win2D the text you are drawing is rasterized using DWrite & Direct2D at runtime.  This will load font data, convert to curves and rasterize (with antialiasing) in the middle of your draw call.

The Win2D version has the benefit that the DrawText call will always give you high quality font rendering at any size, supporting the same full range of characters as the OS (eg for all languages and character sets).  Compare this with XNA sprite fonts where you have a much more limited set of characters (essentially just ASCII) for a fixed size.

There's a tradeoff here.  The XNA approach allows for consistent rendering performance.  The Win2D approach allows for more complete and rich text rendering functionality.

The differences in behavior that you are seeing between desktop and phone are likely related to how much memory and what the display DPI is.  Your PC is likely to be set to 96 DPI (aka 100% scaling), while the 950 XL is set to something like 432 DPI (or 450% scaling) -- I don't have a 950 XL handy to confirm the exact scaling here.

This DPI difference means that your 100 high text is 100 pixels high on PC, but more like 450 pixels high on the phone - so the phone has to work harder than the PC in this case as well.

**Comment by BrianBergh** [comment] 2015-12-30 20:39
Hi again Damyan Pepper.
I have now tried your suggested approach, rendering the text to a renderTarget, and then just drawing that renderTarget (as a sprite). It doesn't change anything, its still dropping to 30 fps after a few seconds of run, and then up to 60 again over and over again. And i still see the laggy glitches in the scrolling. 

I can't believe it should be so hard to make a simple text scroll (slide) smooth over the screen?
(if i do the same using a XAML animation storyboard), it runs absolutely smooth all the time.

**Comment by damyanp** [comment] 2015-12-30 20:43
Can you share your complete example in a git repo somewhere please - so we can be sure that we're looking at the same thing?

**Comment by BrianBergh** [comment] 2015-12-30 20:49
Hi Damyan.

 

Here is a OneDrive link to the complete solution:

https://onedrive.live.com/redir?resid=2318ED6989208AF0!126569 <https://onedrive.live.com/redir?resid=2318ED6989208AF0!126569&authkey=!AB2stDUwepICChU&ithint=file%2crar> &authkey=!AB2stDUwepICChU&ithint=file%2crar

 

Cheers

Brian Bergh

 

 

 

Fra: Damyan Pepper [mailto:notifications@github.com] 
Sendt: 30. december 2015 21:43
Til: Microsoft/Win2D <Win2D@noreply.github.com>
Cc: Brian Bergh <brian.bergh@outlook.dk>
Emne: Re: [Win2D] Lumia 950 XL (Windows 10) - Performance (#216)

 

Can you share your complete example in a git repo somewhere please - so we can be sure that we're looking at the same thing?

**Comment by damyanp** [comment] 2015-12-30 21:03
Could you share this in a git repo please rather than a rar file?  Somewhere where I can view the project in plain text without having to download it to my PC?  Thank you.

**Comment by BrianBergh** [comment] 2015-12-30 21:05
I have no idea how to do that, can you guide  me?

**Comment by damyanp** [comment] 2015-12-30 21:06
https://help.github.com/articles/create-a-repo/

**Comment by BrianBergh** [comment] 2015-12-30 21:13
That was beyond my skills. Nothing to it really.
1. Create a blank UWP app
2. Add a CanvasAnimatedControl as root object (instead of the Grid) with default properties.
3. This is the C# code behind on the page:

using Microsoft.Graphics.Canvas;
using Microsoft.Graphics.Canvas.Text;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Numerics;
using System.Runtime.InteropServices.WindowsRuntime;
using Windows.Foundation;
using Windows.Foundation.Collections;
using Windows.UI;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Controls.Primitives;
using Windows.UI.Xaml.Data;
using Windows.UI.Xaml.Input;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Navigation;

// The Blank Page item template is documented at http://go.microsoft.com/fwlink/?LinkId=402352&clcid=0x409

namespace win2dTest
{
  /// <summary>
  /// An empty page that can be used on its own or navigated to within a Frame.
  /// </summary>
  public sealed partial class MainPage : Page
  {
    public MainPage()
    {
      this.InitializeComponent();
      
    }
    Vector2 scrollPos = new Vector2();
    float speed = 100f;
    float tw = 0;
    private void canvas_Update(Microsoft.Graphics.Canvas.UI.Xaml.ICanvasAnimatedControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedUpdateEventArgs args)
    {
      float elapsed = (float)args.Timing.ElapsedTime.TotalSeconds; // calc once, for speed.
      scrollPos.X -= (elapsed * speed);
      //if (scrollPos.X < -scroller_layout.DrawBounds.Width)
      if (scrollPos.X < -scrollerTarget.Bounds.Width)
      {
        scrollPos.X = tw;
      }
    }
    string about = "This is just a scrolling demo";// with a very long text to see how it works on Windows Phone (Lumia 950 XL).";
    CanvasTextFormat scroller_format = new CanvasTextFormat { FontSize = 50.0f, WordWrapping = CanvasWordWrapping.NoWrap };
    CanvasTextLayout scroller_layout = null;
    //FPSCounter fpsCounter = new FPSCounter();
    CanvasRenderTarget scrollerTarget;
    private void canvas_Draw(Microsoft.Graphics.Canvas.UI.Xaml.ICanvasAnimatedControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedDrawEventArgs args)
    {
      args.DrawingSession.DrawImage(scrollerTarget, scrollPos);
      //fpsCounter.Draw(args.DrawingSession);
    }
    private void canvas_Loaded(object sender, RoutedEventArgs e)
    {

    }
    private void canvas_CreateResources(Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedControl sender, Microsoft.Graphics.Canvas.UI.CanvasCreateResourcesEventArgs args)
    {
      scroller_layout = new CanvasTextLayout(canvas, about, scroller_format, 0.0f, 0.0f);
      scrollPos = new Vector2((float)canvas.ActualWidth, ((float)canvas.ActualHeight / 2) - ((float)scroller_layout.DrawBounds.Height / 2));
      tw = (float)canvas.ActualWidth;

      scrollerTarget = new CanvasRenderTarget(canvas, (float)scroller_layout.LayoutBounds.Width, (float)scroller_layout.LayoutBounds.Height);
      using (CanvasDrawingSession drawingSession = scrollerTarget.CreateDrawingSession())
      {
        drawingSession.Clear(Colors.Blue);
        drawingSession.DrawTextLayout(scroller_layout, new Vector2(0,0), Colors.White);
      }
    }
    private void canvas_SizeChanged(object sender, SizeChangedEventArgs e)
    {

      tw = (float)canvas.ActualWidth;
    }
  }
}

**Comment by BrianBergh** [comment] 2015-12-30 21:42
Hi. I just managed to create a repo with the project. Here it is:
https://github.com/BrianBergh/Win2dTest

**Comment by damyanp** [comment] 2015-12-31 00:49
Thanks, that's helpful - especially seeing the same FPSCounter that you were looking at (I thought you were referring to the FPS display that you get when you run the app in debug mode).

The small glitches during rendering I do also see on my 640.  We currently have 2 items on the [backlog](https://github.com/Microsoft/Win2D/wiki/Backlog) in the performance section that I think are relevant to this, and we're planning to spend time investigating them.

**Comment by damyanp** [comment] 2016-01-08 20:28
Just a quick update since we've been investigating this issue this week.  The problem here is not one of the GPU or CPU not being fast enough to complete the workload.  The issue is one of synchronization.  Win2D attempts to put the game loop thread to sleep while it has nothing to do.  We do this to prevent it from running the battery down (aka turning phone into a hand warmer).  However, the mechanism Win2D uses to determine when to wake up again (WaitForVBlank) turns out to not be as reliably consistent across all GPUs.

Sometimes we'd end up missing a frame because we woke up too late or early.  (In the early case we wake up just before the vblank, realize that there's nothing to do but end up waiting for the next vblank again).

So we're investigating ways to tweak the game loop so that it still has reasonable power usage but avoids this problem.

**Comment by BrianBergh** [comment] 2016-01-08 22:28
@damyanp Thanks for the update. I'm following the investigation closely ;)
Imo. smooth animation has a higher priority than battery life, if i had to pick one.

**Comment by BrianBergh** [comment] 2016-01-19 18:22
1. Any progress in this issue?
2. Why bump the nuget version up to 1.15.0, when nothing is changed? - Or did i miss something?

**Comment by damyanp** [comment] 2016-01-19 18:56
Hi - version 1.14, released today, contains several changes related to this issue.  We've added instrumentation around much of CanvasAnimatedControl's game loop.  In doing so we identitified an issue: sometimes the game loop would unnecessarily wait for a vblank, resulting in a missed frame.  This was resolved with e8f0692ce18dec1059266391cf07b6a9e55d35d3.  This does improve the test cases we've been looking at, but the result is not 100% locked at 60 FPS.

The human eye does seem to be particularly sensitive to scrolling text and so if a frame is lost for any other reason (eg the GPU is busy doing other work for the phone) then this is much more noticable with scrolling text than it is on, say, the particle system demo in example gallery.

It is possible to write a version of a text-scroller that is less sensitive to the occasional missed frame by using variable timing (setting IsFixedTimeStep to false).  Updating the scroll amount by draw count rather than the time reported by ElapsedTime may also result in text that appears to scroll more smoothly.  If the only goal is smooth scrolling text, however, this is something that may be better achieved using the compositor (via XAML animations or the Windows.UI.Composition API).

Thanks for the report that helped us to figure out a way to instrument this, and come up with the vblank fix.

As we have no further work planned in this area I'm closing this issue.

**Closed by damyanp** 2016-01-19 18:56 UTC
Labels: bug

**Comment by BrianBergh** [comment] 2016-01-19 21:24
Hi Damyanp.
Thank you for the feedback.

I can understand what you are saying about changing the timestep and also make changes to how the scroller gets updated. I'm pretty sure that the way i do it in the provided sample https://github.com/BrianBergh/Win2dTest is the most common way of timing any moving object. By calculating the speed based on elapsed time since last movement.

Anyway, I'm not that nerdy about it, and you might have a point there.
However, I have updated the sample (test) i did, to check out your theory about the fixed vs variable timestep. And noticed a few things that made me wonder, am i doing it wrong, or is there still a bug in the timing loop.

When i set the control to IsFixedTimeStep = true, strange things starts to happen (imo) (both on my PC which is a real monster power pc) and on the Lumia 950 XL. The "IsRunningSlowly" starts to flicker (on/off) randomly. (@60fps, and with the simplest draw and update you could possible imagine).

I then tried to tweak it further, by adding more controls to the sample, to see what was going on, here is what i got so far:

When you set IsFixedTimeStep to true, and TargetElapsedTime to 16.6666ms, it should run @60fps. And it does (or close to). but what's strange is that even @60fps, the IsRunningSlowly starts to flicker, and the smoothness also seems to glitch even more. If i set the TargetElapsedTime to 15 (apx 66.66FPS), it goes completely bananas! - the IsRunningSlowly flickers very fast like evert 10th frame or so, it goes on, then off, then on...and so on. And the execution of the frames gets very unstable and glitching. It lags, as if it were running at 10fps.

If i set the TargetElapsedTime to 10 or less, the update event gets called at the expected frequency, but now the drawing goes completely bananas, and IsRunningSlowly is more or less on all the time, even though that's absolutely not true! The CPU is doing <1% , and the fps keeps up just fine?

Another thing: Why is only the Update event affected by the timing? - It seems that the draw renders @60FPS no matter what i do? - It might be by design, and if that's the case, it just fine. Then i just don't get why it is so hard to get it steady without glitches? - In the 90's i was able to do just that on my AMIGA 500 (with a text scroller 10 times more advanced than the one in my sample, with floading flames, and waving sinus effects), and with a cpu running @7mhz. I know it's a much lower resolution and less colors etc. But, .. come on! (2+GHZ * 8 vs 7MHZ), and a billion times faster GPU.

It might just be me, but i don't understand why a simple text (or any bitmap) moving on the screen at a pretty slow and smooth speed, can't be done without glitches on such a powerful hardware?

I know you mention that human eyes are sensitive to text scrolling. But, it could as well be a ball or any other bitmap, it would still create glitches. Which i just can't accept/understand?

As mentioned before, i even did a similar sample for XNA on Windows Phone 7.8, and using a Lumia 925. It runs perfectly smooth without any glitches at all! - It even runs smoother in the emulator (which is software-rendered on my pc for some unknown reason), than the new win2d runs on my actual hardware. If both XNA and Win2D used DirectX which uses the hardware as direct as possible, i just can't understand it? - Sorry for being such a pain in the ... I'm on your side, and i LOVE what you're doing, i just want to help/understand.

Cheers, and thanks for a great job so far :)

**Comment by damyanp** [comment] 2016-01-19 21:44
I suggest you move further down the stack if you want to investigate this further - for example, try taking Win2D or XAML out of the equation by starting with the C++ DirectX11 App or C++ DirectX11 and XAML App templates.

Note that setting the target framerate to anything other than the refresh rate of your primary display will result in IsRunningSlowly being set more often.  This is the update catchup at work.

**Comment by BrianBergh** [comment] 2016-01-20 05:39
@damyanp 
I'm sorry, but my C++ skills are no sufficient for that task, I'm affraid.

About the "IsRunningSlowly", thanks for the info.
It seems that this is never going to be my API for animated graphics, i guess. As it seems to stall here for me, if i can't make an object move from a to b, without glitching :(

I've created the text-scroller sample in pure XAML animation, and it runs smooth without any glitches on both the pc and phone.

Too bad that the new Win2D API isn't up for such a simple task :( I just hoped it could be a replacement for XNA (i was about to start porting some of my games).

Thanks again,
Brian Bergh
