### ISSUE TITLE
D2D DEBUG WARNING - A large number of unreleased interfaces were found

### ISSUE THREAD

**Issue by PatrickSCLin** [Microsoft/Win2D#207] opened 2015-12-17 15:41 UTC
I create a D2D1Device with D2D1_DEBUG_LEVEL_INFORMATION on C++ side, 

and interop it to CanvasDevice for create CanvasSwapChain, set a timer run every 30ms on C# side,

the console just print a lot warning, crash about 5+ minutes later.

```
D2D DEBUG WARNING - A large number of unreleased interfaces were found. Currently there are [12001] unreleased interfaces allocated by this DLL.
D2D DEBUG WARNING - A large number of unreleased interfaces were found. Currently there are [13001] unreleased interfaces allocated by this DLL.
D2D DEBUG WARNING - A large number of unreleased interfaces were found. Currently there are [14001] unreleased interfaces allocated by this DLL.
D2D DEBUG WARNING - A large number of unreleased interfaces were found. Currently there are [15001] unreleased interfaces allocated by this DLL.
D2D DEBUG WARNING - A large number of unreleased interfaces were found. Currently there are [16001] unreleased interfaces allocated by this DLL.
D2D DEBUG ERROR - A rental threaded interface [00000000] was simultaneously accessed from multiple threads. 
```

**Comment by PatrickSCLin** [comment] 2015-12-17 16:28
here is the sample

**Comment by damyanp** [comment] 2015-12-17 17:33
You have a couple of QueryInterface calls where you store the result in a raw pointer and don't call release on them:

_dxgi_surface_interface: [YUVHelper.cpp line 95](https://github.com/PatrickSCLin/YUVSample4/blob/master/Win2D_YUVHelper/YUVHelper.cpp#L95) 

_d2d_context2: [YUVHelper.cpp line 101](https://github.com/PatrickSCLin/YUVSample4/blob/master/Win2D_YUVHelper/YUVHelper.cpp#L101) 

Use a ComPtr for these and those two leaks at least will be fixed.

**Comment by shawnhar** [comment] 2015-12-17 18:01
Odd, I don't see any warnings when running this...

**Comment by PatrickSCLin** [comment] 2015-12-17 19:49
don't know why, if i use ComPtr for _dxgi_surface, then it will crash

**Comment by PatrickSCLin** [comment] 2015-12-17 19:54
you need to wait for minutes, I was running in 2011 MBP, graphics card: HD3000

it will counts from 1001 to 10000 then crash...

![capture](https://cloud.githubusercontent.com/assets/2464698/11880269/ba13afac-a53a-11e5-8d22-59fd82d0697a.PNG)

**Comment by damyanp** [comment] 2015-12-17 20:39
On [line 107](https://github.com/PatrickSCLin/YUVSample4/blob/master/Win2D_YUVHelper/YUVHelper.cpp#L107) you do &_dxgi_surface.  I don't think you mean this - it should be _dxgi_surface.Get() (assuming you've made _dxgi_surface a ComPtr).

**Comment by damyanp** [comment] 2015-12-17 21:10
I'm seeing some problems I don't understand when I run this locally.  I'll keep looking.

**Comment by damyanp** [comment] 2015-12-17 21:32
I've added an item to our backlog to investigate this further.  It'll be next week at the earliest.

**Comment by PatrickSCLin** [comment] 2015-12-18 06:39
I found it would throw exception when CanvasVirtualBitmap (which created in C++) doing dispose,

Exception thrown at 0x77B43E28 in Sample.exe: Microsoft C++ exception: HResultException at memory location 0x05C3F254.

**Comment by PatrickSCLin** [comment] 2015-12-18 06:51
I'm new to C# & C++/CX interop, is anywhere I done wrong ?

https://github.com/PatrickSCLin/YUVSample4/commit/4304a37702c56c94cf11436dd0fd850521ba6739

**Comment by damyanp** [comment] 2015-12-18 17:38
I didn't spot anything obviously wrong, but this is essentially the error I was seeing.  I did observe that not setting CanvasDevice.DebugLevel prevented this problem.  That's where I'm going to start my investigation when I get back to this.

**Comment by damyanp** [comment] 2015-12-21 20:05
Hi Patrick,

Ultimately, this issue is caused by a bug in the Direct2D debug layer which means that the ID2D1ImageSource object you are passing to CanvasVirtualBitmap violates the COM identity rule.  This rule says that if you QueryInterface an object for IUnknown then you should always get the same IUnknown instance back.  However, the ID2D1ImageSource object you get from CreateImageSourceFromDxgi, can sometimes return different IUnknown instances when the debug layer is enabled.

Win2D relies on COM identity to make the "Get" part of "GetOrCreate()" work.

I've filed a bug on the Direct2D team for this (for my reference, this is 5944573).

As this cannot be fixed in Win2D I'm going to close this issue.  As a workaround, I would suggest that you don't set CanvasDevice.DebugLevel. 

Thanks for taking the time to report this and providing a nice repro!

**Closed by damyanp** 2015-12-21 20:05 UTC
Labels: bug, external

**Comment by damyanp** [comment] 2015-12-21 21:07
Also: the "large number of unreleased interfaces were found" was unrelated to the behavioral problems you were seeing and were a red herring.  However, it did show that CanvasDrawingSession was holding on to a few (small) resources longer than it should (ie it was releasing them when garbage collected, rather than when disposed).  This will be fixed in the next release.

**Comment by PatrickSCLin** [comment] 2015-12-22 08:31
thanks for help! it runs well now :+1:
