### ISSUE TITLE
'Sleep' API and the Windows (Phone) Store

### ISSUE THREAD

**Issue by dumbledad** [Microsoft/Win2D#114] opened 2015-07-09 22:03 UTC
We've just had our app bounced from the Windows Phone Store with the following failure:

Error Found: The supported APIs test detected the following errors: this API is not supported for this application type - Api=Sleep. Module=api-ms-win-core-synch-l1-2-0.dll. File=Microsoft.Graphics.Canvas.dll.

How did you guys get past this when pushing your app into the store?

**Comment by shawnhar** [comment] 2015-07-09 23:02
Are you sure this error actually came from the Store submission process (did you get an email about it from the Store process?) or was it reported on your local PC while running the Windows App Certification Kit?

If it is the latter, you are probably using an outdated version of Windows App Certification Kit.

**Comment by dumbledad** [comment] 2015-07-10 00:35
Yep - it's from the store submission process. I'm just checking with a colleague that we submitted a release build (not a debug build) as it looks like that may cause the same fail. I'll follow-up here when I know.

**Comment by dumbledad** [comment] 2015-07-10 20:14
Unfortunately that's not the issue - it was a release build, submitted to the store.

**Comment by shawnhar** [comment] 2015-07-10 20:37
Can you share more details about what version you are using?   I published an updated version of Example Gallery to the Store just this Monday, and that worked using:

- Latest ExampleGallery.81.sln from http://github.com/Microsoft/Win2D-Samples
- Win2D version 0.0.22
- Visual Studio 2013 Update 4
- Release ARM flavor

**Comment by dumbledad** [comment] 2015-07-10 20:46
We are 
* Win2D 0.0.20
* Visual Studio 2015 
* Release ARM flavor

**Comment by shawnhar** [comment] 2015-07-10 20:49
8.1 app, or UWP?   (the Store is not open for publishing UWP yet)

**Comment by dumbledad** [comment] 2015-07-10 21:09
Windows Phone 8.1, but taken from one of those 'Universal' VS templates that gave a Windows, Windows Phone 8.1, and Shared 'project'. But not UWP

**Comment by shawnhar** [comment] 2015-07-10 21:14
Thanks for the details.  I will do some digging into this - not sure what's up here!

**Comment by ankohanse** [comment] 2015-07-14 07:12
Just got the exact same issue when trying to publish a new version of my product to the store. Details:
Window Phone 8.1 project (using universal app template), 
Release ARM
Win2D 0.0.22
Visual Studio 2013 Update 5 RC

![win2d_sleep](https://cloud.githubusercontent.com/assets/11971893/8668168/20a24a4e-2a5c-11e5-992b-af9c61e80e9b.png)

**Comment by ankohanse** [comment] 2015-07-14 10:04
Some additional info: the app does succeed on the 'Windows App Certification Kit' (Visual Studio 2013 Update 5 RC).
But when then submitted to the app store, the submission is rejected with the above error.

Or is this an issue of the app store itself? Who to contact?

**Comment by shawnhar** [comment] 2015-07-14 13:53
This appears to be a Store issue.  I'm discussing with the Store team and will update here with what I find out.

**Comment by shawnhar** [comment] 2015-07-14 17:41
dumbledad and ankohanse, would you mind sharing the title and app ID of your apps that were rejected?  (the Store team needs this info).

Feel free to use http://blogs.msdn.com/b/win2d/contact.aspx if you don't want to share that info in public.

Thanks!

**Comment by shawnhar** [comment] 2015-07-15 01:13
ankohanse, please resubmit your app.  The Store team is still investigating the root cause of this problem, but in the meantime they set up a temporary waiver for your app ID that will ignore this false positive and allow it to be published.

dumbledad, we can do the same for you once we know your app title and ID.

Thanks and sorry for the inconvenience!

**Comment by ankohanse** [comment] 2015-07-15 05:05
Hi Shawn,

 

Yes, app has passed this time and is now in the store.

Thank you for your super support!

 

Cheers,

Anko

**Comment by pleaseking** [comment] 2015-07-15 23:35
Hi, same here - can our app be white-listed as well? How do I send you the app ID?

**Comment by shawnhar** [comment] 2015-07-16 00:03
> How do I send you the app ID? 

Either post it here or send it through the contact form on the Win2d blog.

**Comment by pleaseking** [comment] 2015-07-16 09:14
Shawn,

the app ID is 9NBLGGGXZ7S2 .

Thanks!

2015-07-16 3:03 GMT+03:00 Shawn Hargreaves <notifications@github.com>:

> How do I send you the app ID?
>
> Either post it here or send it through the contact form on the Win2d blog.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/Win2D/issues/114#issuecomment-121782170>.
>



-- 
  Best regards,
    Mike

**Comment by gwstroup** [comment] 2015-07-17 04:30
Shawn, 
We are having the same issue and I submitted a request on the contact form above. Can you confirm if you received this request? 

Thanks in advance, 
Will

**Comment by SunboX** [comment] 2015-07-17 08:34
Same for me, did send you a request using the contact form. Have to upload the app today, can you confirm that you received the request?

greetings,
André

**Comment by shawnhar** [comment] 2015-07-17 12:57
Store team is in the process of deploying a fix for this issue.  I will update when that is complete.

**Comment by shawnhar** [comment] 2015-07-17 13:51
This issue should now be fixed.   Please resubmit your apps, and my apologies for the inconvenience!

**Closed** 2015-07-17 17:45 UTC
