### ISSUE TITLE
Ink is drawn thicker during one frame while drying

### ISSUE THREAD

**Issue by Trasteby** [Microsoft/Win2D#278] opened 2016-02-05 11:21 UTC
When using the Example Gallery's ink example, or making an app which dries ink using similar logic, the ink is drawn thicker for one frame during drying. This is a very subtle visual glitch on very pixel-dense devices, like the Surface Pro, but it's easily visible on a standard 24" 1080p screen, and on anything less pixel dense, and especially when drawing thinner ink than the Example Gallery allows, it is a very noticeable and annoying flicker.

The InkSynchronizer class exists for the very purpose of making sure the drying process of ink is synchronized with the removal of wet ink, but it seems Win2D currently makes this impossible to achieve.

One solution could be if the Win2D APIs exposed some way to get notified when rendering is finished (although I'm not sure that's possible and feasible to implement).

This issue was caused by the solution to https://github.com/Microsoft/Win2D/issues/181.

**Comment by shawnhar** [comment] 2016-02-05 15:47
This isn't something Win2D has any ability to improve.

As I mentioned in the comments for 181, DirectInk team is looking into possible root causes of the issue.  Depending on what they find, they might make an improvement in a future version of Windows, but that doesn't help us in the here and now.

Currently, you have two options - wait like the code in Example Gallery does and usually get the ink drawn twice for one frame, or don't wait like the previous version did and vary rarely get a flicker where no ink is visible for one frame.  We chose the former for Example Gallery mostly based on your feedback that the flicker occurs commonly for you, as everyone here is still unable to repro it more than roughly 1 time in 1000.

**Comment by shawnhar** [comment] 2016-02-08 15:20
Closing issue as we have no plans (or ability!) to make any changes in Win2D here.

Thanks!

**Closed by shawnhar** 2016-02-08 15:20 UTC
Labels: bug
