### ISSUE TITLE
D2D tile rendering appears with a line on the Texture boundary

### ISSUE THREAD

**Issue by deepsinha131** [microsoft/Win2D#726] opened 2019-09-24 12:36 UTC
The steps of drawing I did was:
Acquire DXGI surface context (11 on 12 Device) For a DX12 texture -> beginDraw -> pushAxisAllignClip -> push matrix -> draw paths ->pop matrix -> popAxisAlignedClip -> endDraw ->release Texture

![Line bug copy](https://user-images.githubusercontent.com/55747256/65512164-50c63980-def6-11e9-9bd9-0d1e1bb8db53.jpg)

Finding:
This issue does not occur if I setAntiAliasing() Mode as Aliased before starting of beginDraw(). But without any anti aliasing mode set in device context, these lines appears at boundary edges of the tile which is rendered. Need to resolve such bugs with D2D drawing in my app.

I referred these links for D2D drawing:
https://docs.microsoft.com/en-us/windows/win32/direct2d/devices-and-device-contexts
https://docs.microsoft.com/en-us/windows/win32/direct3d12/d2d-using-d3d11on12

**Comment by shawnhar** [comment] 2019-09-24 16:09
You don't fully explain how your drawing works here, but if I follow correctly that you are drawing multiple rectangles and seeing a gap in between adjacent ones, then this sounds like the expected behavior.  Antialiasing works by softening the edges of geometry, which is often a good thing for visual quality but not what you want when trying to exactly cover every pixel.  With antialiasing enabled, the background can show through the soft edges in between two adjacent tiles.  Solution is to disable AA, or make sure your tiles exactly line up to pixel locations (which is equivalent to disabling AA, but can be more complex as you'll have to account for DPI scaling etc.)

**Comment by deepsinha131** [comment] 2019-10-10 16:27
@shawnhar apologies for the late reply on this. Tiles are important in my drawing to optimize on higher drawing sizes. The drawing works on rectangles/tiles on the canvas. Suppose I draw a stroke on canvas with n tiles, and the stroke appears on only x out of n tiles, the issue here is that the boundary/edges of the tiles gives these lines or shows the background. 

As you mentioned the best approach here would be to disable AA, but I need AA on the actual stroke and just not on the tile boundaries as the geometry I am providing is the geometry inside each tile. My expectation here is that AA would not get applied on the actual edges of the tile canvas/area. My expectation here is that AA would not get applied on egdes specially when they are simple rectangles with already smooth edges. Is there a way to get this tweaking? The effect is not providing a good drawing experience at present.

**Comment by shawnhar** [comment] 2019-10-10 18:58
There is no way to enable AA only for some edges but not others.   There are two ways to draw a hard edge without any AA:

1. Disable AA
2. Or exactly align the edge to an output pixel location  (which will require understanding and taking into account any high DPI dips vs. pixels adjustment)

**Comment by deepsinha131** [comment] 2019-10-11 20:38
I agree but the issue I am pointing out is that suppose I create a drawing rect and draw a stroke inside that rect. Now I apply AA effect on the strokes inside the rect. Why is there a AA affect on the boundaries of the rect, the AA should only be on the edge of the stroke is it not?. Shouldnot the effect be only applicable for the drawn paths and not the canvas edges. If the entire rect is filled then also there shouldnot be any AA on the boundaries. 

In this case, I am using the below concept to clip drawing tiles:
        _deviceContext->PushAxisAlignedClip(
            D2D1::RectF(clip.xmin, clip.ymin, clip.xmax, clip.ymax),
            D2D1_ANTIALIAS_MODE_PER_PRIMITIVE);
Is this taking making some AA effect on the boundaries of clip?

Secondly, can I get some documentation as to how I can allign the boundaries specially for AA effect. I have already taken care of this when no AA affect is applied. There is no gap in my allignment to actual pixel location. Either some float to Integer conversion is occurring for AA effect.

**Comment by shawnhar** [comment] 2019-10-11 20:59
I just realized a possible point of confusion - are you using Win2D, or native Direct2D?  I was assuming you were talking about Win2D, since this issue was created in the Win2D repository, but the code you share above is not Win2D.

**Comment by deepsinha131** [comment] 2019-10-11 21:14
Ohh my bad here, sorry for the confusion, can you point me to the right forum?

**Comment by shawnhar** [comment] 2019-10-28 22:33
Closing external as this is not a Win2D issue.

**Closed by shawnhar** 2019-10-28 22:33 UTC
Labels: external, question
