### ISSUE TITLE
Alpha channel in PixelShaderEffect does not work as expected

### ISSUE THREAD

**Issue by h82258652** [Microsoft/Win2D#959] opened 2024-06-24 08:16 UTC
Hello, I'm using the `PixelShaderEffect` on my project. But I found the alpha channel does not work as expected.

Here is my shader code.
```HLSL
#define D2D_INPUT_COUNT 0

#include "d2d1effecthelpers.hlsli"

D2D_PS_ENTRY(main)
{
    return float4(1, 0, 0, 0);
}
```
And the xaml code.
```XAML
    <Grid Width="600" Height="200">
        <Grid.ColumnDefinitions>
            <ColumnDefinition />
            <ColumnDefinition />
            <ColumnDefinition />
        </Grid.ColumnDefinitions>
        <Border Grid.ColumnSpan="2" Background="Blue" />
        <win2d:CanvasControl
            Grid.Column="1"
            Grid.ColumnSpan="2"
            CreateResources="OnCreateResources"
            Draw="OnDraw" />
    </Grid>
```

As expected, the color should be transparent and it should look like only the blue border is rendering.
But actually I get this:
![image](https://github.com/microsoft/Win2D/assets/5144550/c848e96a-612c-49d7-9153-0817250158f3)

Here is the repo.
[PixelShaderBugDemo.zip](https://github.com/user-attachments/files/15951825/PixelShaderBugDemo.zip)

### Environment
Windows 11 Enterprise 22635.2915

### NuGet package version
[Win2D.uwp 1.27.1](https://www.nuget.org/packages/Win2D.uwp/1.27.1)

**Comment by Sergio0694** [comment] 2024-06-27 01:04
Closing this as by design, as the issue is custom shaders produce unpremultiplied output. This can be fixed by plugging them into a `PremultiplyEffect` before drawing them. I talked offline with @h82258652 and he could get his code working correctly.

**Closed as not planned by Sergio0694** 2024-06-27 01:04 UTC
