### ISSUE TITLE
Crash dump in Win2D (UWP / Win2D 1.17)

### ISSUE THREAD

**Issue by eriadel** [Microsoft/Win2D#338] opened 2016-04-30 07:56 UTC
Hi Shawn and Damyan,

Finally, we've reproduced crash dump, which is hunting us in the MS Store since 2 months.
Could you take a look on it ?

Dump file:
https://drive.google.com/open?id=0B4Q_unSUoNlUaVBqcFQ3d3JOSlU

Callstack screenshot:
https://drive.google.com/open?id=0B4Q_unSUoNlUdFpJVjRQZmQtdm8

Please let me know, if you need anything.

(there's another strange artifact we observe during tests, but that's separate topic and I would be appreciated if we can fix this case at the first place).

Cheers!
Karol

**Comment by damyanp** [comment] 2016-05-02 16:55
This looks like the call stack you get when the application throws an exception that is not handled.  Note that the top method on the call stack is the unhandled exception handler.  Unfortunately, it doesn't look like it is possible to get further information from a crash dump:

![image](https://cloud.githubusercontent.com/assets/8118402/14960905/e61e3f6e-104b-11e6-980b-130f7f1ce8f6.png)

If you are able to debug the live in a debugger then you should be able to look at the values of e.Exception and e.Message and get a better idea what is going on.  Also, defining "DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION" should give you a local repro that closer matches when happens in non-debug builds.

**Comment by eriadel** [comment] 2016-05-03 06:51
Damyen, pls disable "just my code" in the VS2015 Debug settings. Open the dump in MS Visual Studio 2015 and press "Debug with Mixed". Then, when all symbols will be loaded you should see a beautiful call stack in the native code (including Win2D activity) as attached in the screenshot above..

**Comment by damyanp** [comment] 2016-05-03 16:40
Yes, my callstack matches yours.

This looks like you are able to reproduce this using some kind of a test app.  Are you able to share this so we can get a live repro?

**Comment by eriadel** [comment] 2016-05-03 16:53
Yes I can share a test app with you, but this require 2 things:
1.) Our test apps bases on improved Win2D shaders/particles engine library which is part of our portable UI library. We do not see any problems, if you like to use our refined solutions, as we've needed to add many security additions to the Win2D examples, but I would not like to share this code to public. We would like to ask you, to not share this code at any circumstances..
2.) Please provide me an email I can share you our test app with our code via email.

**Comment by damyanp** [comment] 2016-05-03 17:04
Ok.  My email address is my git user name @microsoft.com.

In the meantime, if you're able to reproduce this locally then if you enable mixed/native debugging and set it to break on all C++ exceptions then you may be able to get the debugger to break inside std::_Check_C_return as while in a std::unique_lock.

The reason I'm unsure about this is that when I contrive a repro of this I don't see the same unhandledexception handler get called.  Anyway, I can build a fix for that and we can see if it addresses your issue.

**Comment by damyanp** [comment] 2016-05-04 17:54
I've pushed the fix to the fix to the issue I found with recursive mutexes that I spotted - it's commit https://github.com/Microsoft/Win2D/commit/a4cb201a54363397a2500b00bccf20b3ecdea99d.  If you're able to clone the Win2D repro and run the "build" script then that will generate a local nuget package that you can try your project against.  Or you can wait for the next official release.

As I said though, I'm unsure if this is the same thing that you're seeing because when I contrive this to happen locally I don't see the unhandled exception handler fire.  But it may be.

**Comment by eriadel** [comment] 2016-05-04 18:38
Damyan, I appreciate that. This is not easy to reproduce issue even locally.(at least not on my machines) That could be. There's kind of mutex call in the callstack.

We needed 1 day to reproduce the issue, even having dedicated tests.

I need like 1 week to strip our UI lib from parts you do not need, to send you a test app.
I will also explain another memory leak we observe, when the UWP windows is minimized and the test is running. Please give me few days... you will get all soon!

Thanks for a quick support. As UWP is our second priority after cross platform web dev. I need few days to give you everything we have.

**Comment by shawnhar** [comment] 2016-05-10 15:29
I'm going to close this issue as it sounds like https://github.com/Microsoft/Win2D/commit/a4cb201a54363397a2500b00bccf20b3ecdea99d has fixed the problem.  Thanks for the crash dump!

**Closed** 2016-05-10 15:30 UTC
Labels: bug, need info

**Comment by eriadel** [comment] 2016-05-10 18:00
thanks for the fix! 

if there will be something wrong in the MS store in the next months, then we will try to obtain another one for you... (crossing fingers for no more issues;)
