### ISSUE TITLE
Cannot set float2 property on PixelShaderEffect from C++

### ISSUE THREAD

**Issue by chuckries** [Microsoft/Win2D#422] opened 2016-09-01 22:02 UTC
My shader file has a field `float2 textureSize`. From C++ I am trying to set 
```C++
_effect->Properties->Insert("textureSize", float2(256.0f, 224.0f));
```
where _effect is a `PixelShaderEffect^`.

When I run this code I get a COMException of E_INVALIDARG with the message that textureSize is a Vector2. What am I doing wrong?

**Comment by chuckries** [comment] 2016-09-01 23:29
what info do you need?

**Comment by shawnhar** [comment] 2016-09-02 00:09
Is this on 8.1 or UAP?

**Comment by chuckries** [comment] 2016-09-02 00:09
UAP

**Comment by shawnhar** [comment] 2016-09-02 00:11
This sounds like something is not working about the C++/CX compiler numerics projection.

Please share a repro app.

**Comment by shawnhar** [comment] 2016-09-13 03:56
Closing issue due to lack of a repro app to show the problem you are seeing.   Feel free to reactivate if you are able to provide a repro.

**Closed by shawnhar** 2016-09-13 03:56 UTC
Labels: need info

**Comment by chuckries** [comment] 2016-09-13 18:41
[Repro Project](https://github.com/chuckries/Win2DRepro/). Repro steps are in readme. Basically just open in VS 2015 and F5.

**Comment by shawnhar** [comment] 2016-09-13 21:30
Thanks for the repro - I understand what is going on here now.  This is a bug in the C++/CX compiler, which I will report to that team.  Unfortunately it is not something we will be able to work around in Win2D.

The issue is that the type projection logic which makes the WinRT Vector2 type show up as a C++ float2 struct is not getting applied when these types are boxed into an Object^.  This means that when a float2 is passed into a loosely typed API such as PixelShaderEffect.Properties, it gets boxed incorrectly, so when Win2D then tries to QI for an IReference<Vector2>, it can't find that because the compiler gave it an IReference<float2> instead  (float2 is purely a type that exists inside C++/CX - WinRT and Win2D don't know anything about this type).

A workaround would be to declare this parameter as an array (float[2]) instead of vector (float2).
