### ISSUE TITLE
CanvasVirtualControl doesn't create resources when loaded.

### ISSUE THREAD

**Issue by coder89** [Microsoft/Win2D#492] opened 2017-02-17 09:33 UTC
CanvasVirtualControl does not create VSIS target and therefore does not call CreateResources. Also all calls to Invalidate() or InvalidateRect() are ignored and there is no good way to force the canvas to initialize itself. Our XAML tree in a prototype app looks like this:

`<Page>`
`<Grid>`
`<Border>`
`<UserControl>`
`<Grid>`
`<CanvasVirtualControl (stretched both direction) />`
`<InkCanvas (stretched both direction) />`
`</Grid>`
`</UserControl>`
`</Border>`
`</Grid>`
`</Page>`

One way to force this to initialize is to create a method like this:
`void EnsureCanvasInitialized()`
`{`
`    if (!m_isWin2dInitialized.exchange(true))`
`    {`
`        m_win2dCanvas->ClearColor = Windows::UI::Colors::Black;`
`        m_win2dCanvas->ClearColor = Windows::UI::Colors::Transparent;`
`    }`
`}`

And call it whenever you expect the canvas to be initialized, i.e. events like PointerEntered, InkStrokeStarted, or simply whenever you need to redraw the canvas... that is before calling Invalidate.

Feels like a bug to me. If you need access to the prototype app, which is 100% repro of this issue, just send me a PM.

**Comment by shawnhar** [comment] 2017-02-17 13:50
This sounds like the same issue as #479?

**Comment by coder89** [comment] 2017-02-17 17:04
Yes, it looks like my issue report is a duplicate of this one. Sorry, I missed it.

**Comment by shawnhar** [comment] 2017-02-21 13:46
Closing since this is a dupe of #479

**Closed by shawnhar** 2017-02-21 13:46 UTC
