### ISSUE TITLE
CanvasControl into flyout 

### ISSUE THREAD

**Issue by AlexRoss** [Microsoft/Win2D#183] opened 2015-10-26 08:44 UTC
I do not quite know very well the behavior of win2d, but noticed one strange play singularity. To repeat it  necessary to create  a win8.1 project  with flyout

Xaml
``` 
<Button Content="ShowFlyout" HorizontalAlignment="Stretch" Margin="601,73,685,0" VerticalAlignment="Top">
			<Button.Flyout>
				<Flyout >
					<Grid Height="310" Width="291">
						<Grid.ColumnDefinitions>
							<ColumnDefinition Width="69*"/>
							<ColumnDefinition Width="70*"/>
						</Grid.ColumnDefinitions>
						<Grid.RowDefinitions>
							<RowDefinition Height="23*"/>
							<RowDefinition Height="132*"/>
						</Grid.RowDefinitions>
						<Button Content="Yellow" HorizontalAlignment="Right" Margin="0,7,5,0" VerticalAlignment="Top" Height="32" Width="132" Click="Button_Click"/>
						<Button Content="Red" Grid.Column="1" HorizontalAlignment="Left" Margin="7,7,0,0" VerticalAlignment="Top" Height="32" Width="133" Click="Button_Click_1"/>
						<xaml:CanvasControl x:Name="CControl" Draw="CanvasControl_OnDraw" Grid.ColumnSpan="2" Margin="10" Grid.Row="1" ></xaml:CanvasControl>
					</Grid>
				</Flyout>
			</Button.Flyout>
		</Button>
```
Code 
```
private Color _drawColor = Colors.Green;


        public MainPage()
        {
            this.InitializeComponent();
        }

	    private void CanvasControl_OnDraw(CanvasControl sender, CanvasDrawEventArgs args)
	    {
			args.DrawingSession.Clear(_drawColor);
	    }

		private void Button_Click(object sender, RoutedEventArgs e)
		{
			_drawColor = Colors.Yellow;
			CControl.Invalidate();
		}

		private void Button_Click_1(object sender, RoutedEventArgs e)
		{
			_drawColor = Colors.Red;
			CControl.Invalidate();
		}
```
After starting the app, show Flyout, we see that the canvas  event Draw was invoke , call the buttons events (Yellow & Red button), nothing happens,  now hide flyout and call it again, the events of the buttons redraw canvas.

**Comment by damyanp** [comment] 2015-10-26 16:54
Thanks for reporting this - I can reproduce this behavior.  I've added an item to our backlog to investigate this further.

**Comment by damyanp** [comment] 2015-11-10 22:51
I've had a chance to look further into this.  It looks like this is an issue involving CanvasControl getting loaded/unloaded events from the flyout.  There's a platform issue where loaded/unloaded events are not necessarily being dispatched in the correct order.  This is confusing CanvasControl - so the point at which you call Invalidate() it thinks it is not loaded and so it doesn't redraw.

You can see this at work if you add any control (I tried it with Rectangle) and register Loaded / Unloaded handlers that output debug text.  You should be able to see that you sometimes see "unloaded, loaded" or "loaded, unloaded" when you open the flyout.

I've found that this issue does not reproduce for a Windows 10 app.  I'm not sure exactly what has changed, since I believe the platform still does not guarantee that loaded/unloaded are ordered correctly.  I suspect that flyout has been modified to not issue unloaded/loaded close together.

We've had an item on the [backlog](https://github.com/Microsoft/Win2D/wiki/Backlog) to investigate this for a while and will continue to use this to track this issue.  For this reason I'm going to close this issue with the recommendation that you find a way to work around it for now, or upgrade to a Windows 10 app.

**Closed by damyanp** 2015-11-10 22:51 UTC
Labels: bug
