### ISSUE TITLE
Access violation random crashes (qcdx11um8994.dll)

### ISSUE THREAD

**Issue by hellothisismyaccount** [Microsoft/Win2D#476] opened 2016-12-25 10:55 UTC
Hi, 

I'm using multiple AnimatedCanvasControls on a single page and my UWP app **randomly** crashes without any exception. I can see _access violation_ with native debugging enabled. 

Do you have any idea what can be the cause of it? 
I know this issue is very vague, but even blind guess could be helpful.

![crash](https://cloud.githubusercontent.com/assets/24762476/21470724/eaa50018-ca95-11e6-8cbb-c8e994a10b9d.png)

**Comment by ratishphilip** [comment] 2016-12-26 06:14
A wild guess...
Are you creating any Win2d object (which requires a ICanvasResourceCreator) using one AnimatedCanvasControl and using it in the Draw Handler for another AnimatedCanvasControl?

**Comment by shawnhar** [comment] 2016-12-27 22:02
qcdx11um8994.dll is the Qualcomm user mode graphics driver.  This could be crashing for many different reasons:

1. Bug in the driver
2. Bug in your app, Win2D, or D2D that leads to passing bad data into the driver
3. Lack of proper synchronization when doing multithreaded rendering
4. Driver could be hitting an out-of-memory situation?

If you have native debugging enabled, you should be able to get a callstack in the debugger when this exception is thrown.  That may give more clues what the problem is.

btw. when you say your app uses multiple animated controls, how many are we talking about?  CanvasAnimatedControl is not a great choice if you have many of them active at the same time.

**Comment by shawnhar** [comment] 2017-01-25 04:43
Closing due to lack of actionable information.

**Closed by shawnhar** 2017-01-25 04:43 UTC
Labels: need info
