### ISSUE TITLE
TDR after resuming app on Surface 3 (graphics driver bug)

### ISSUE THREAD

**Issue by SebastianStehle** [Microsoft/Win2D#300] opened 2016-03-10 08:21 UTC
Hi,
I have some issues with the CanvasVirtualControl. Unfortunately this is driven by issues reported by users and often I cannot reproduce it on all devices (I don't have a Surface).

But I have tested it on the phone with the following sample: https://github.com/SebastianStehle/App4 with the following steps:
1. Open the App
2. Close the App
3. Click Suspend in Visual Studio
4. Open the App again

=> It renders correctly, but RegionsInvalidated is never called, I guess it is cached in some way.

Then I made another test.
1. Open the App
2. Close the App
3. Open a lot of other Apps (5-6)
4. Click Suspend in Visual Studio
5. Open the App again

=> The screen is just white and RegionsInvalidated is never called. I also tried to handle the App.Resume event and call Invalidate, but this does not work always.

When this happens I often get a lot of exceptions like you see in the screenshot.
![untitled](https://cloud.githubusercontent.com/assets/1236435/13663371/6e68cbac-e6a1-11e5-8006-6e8dcfb0ec5e.png)

On the Surface this seems to happen very often, but as I mentioned, I don't have a Surface.

**Comment by SebastianStehle** [comment] 2016-03-10 16:44
Any ideas or workarounds? I cant wait to provide a bugfix ;)

**Comment by SebastianStehle** [comment] 2016-03-10 19:02
I dont click the resume button. When I open the app again, the Resuming event is triggered correctly, but when I have opened a lot of other apps in the meantime (like Powerpoint + Word + Excel + Acrobat Reader + ... ) then the canvas is white. I see the button but not the colored regions. As I mentioned it works correctly most of the time.

**Comment by SebastianStehle** [comment] 2016-03-10 20:03
No, I can click the "Overlay" button in the App (have you seen it?) and press the Resume button: No change. Only when I scroll around.

**Comment by SebastianStehle** [comment] 2016-03-10 20:44
I try to explain it again:

1. Start the debugger (the App opens)
2. Close the App using your Phone
3. Click suspend in Visual Studio
4. Open 5-10 other apps
5. Open the app again using your Phone

The result is: 
* The canvas is blank.
* The Application.Resuming event is triggered. 
* The button is rendered and changes the state correctly when you click it (in my main app I can use all other features correctly).

About Step 4: I don't know why you have to open so many apps. I assume that the canvas content is cached in some way, because it renders correctly without a RegionsInvalidated, when you go back to my app immediately. But when you open other apps, the Phone runs low with memory (or any other resource) and the cache entries are deleted.

**Comment by damyanp** [comment] 2016-03-10 20:48
Oh!  This needs to run on the phone.  I thought from the original report that you couldn't repro on phone.  Ok.

What model phone are you testing this on?

**Comment by damyanp** [comment] 2016-03-10 21:04
This does sound similar to #194, which currently is being investigated as a driver bug on Surface Pro 3's.

If you're able to find out whether or not a device has been lost around the time that you're able to reproduce the issue that would help.  Part of the Surface 3 issue is the the device was getting lost every time this particular app was suspended.  

I suspect that there may also be an issue around recovering virtual surface image sources after device lost, but that this very hard to repro since device lost doesn't happen all the often.  If you've found a more solid repro that doesn't involve a Surface then that'd be very helpful.

**Comment by damyanp** [comment] 2016-03-10 21:21
Maybe, on detecting device lost, you could try removing the control and adding a new one?  Or doing a fake navigate away and back to the page?

At the end of the day I think that the underlying XAML control is broken and you need to get a new one to be able to continue.

**Comment by SebastianStehle** [comment] 2016-03-10 21:26
Another idea for an experiment. In my case it renders correctly after scrolling around, so it seems to be able to recover, but I dont have the insights as you guys have.

**Comment by SebastianStehle** [comment] 2016-03-11 12:34
I updated my sample and implemented your suggestion with recreating the canvas control. Unfortunately the device lost event is never triggered, so I just recreate in on each resume. 

https://github.com/SebastianStehle/App4/blob/master/App4/CanvasControlWrapper.cs

It seems to work, what do you think about it?

**Comment by damyanp** [comment] 2016-03-11 17:26
Looks good - I'd be interested to hear if this indeed fixes the issues your users are reporting.

I'd check that when you release the control is really does eventually get garbage collected.  You may want to call RemoveFromVisualTree to be sure (see http://microsoft.github.io/Win2D/html/RefCycles.htm).

**Comment by SebastianStehle** [comment] 2016-03-11 18:18
Good point

**Comment by SebastianStehle** [comment] 2016-03-12 19:09
I have some positive feedback from my users, it seems to work. But this is definitely something you should solve and not a app developer ;)

**Comment by shawnhar** [comment] 2016-05-26 16:08
Update:  we've been digging into the root cause of this, which turns out to be a driver bug that is consistently causing a TDR (device removed error) during suspend/resume on these devices.  We've reported the issue to Intel and will coordinate with them to get the driver fixed.

A secondary issue, which greatly complicates the symptoms of this bug, is that XAML only checks for device removed when it has a need to redraw the display.  Win2D notices device removed either when it comes to draw something, or when notified by XAML.  This means that if no drawing is taking place, neither XAML or Win2D will notice the error state, so the control is never recovered.  Hence why removing and re-adding a new control fixes the problem (because the new control gets a new device) and also why scrolling around corrects it (because that makes Win2D draw something, at which point we notice the error and initiate recovery).  You can see the same behavior if you force a TDR while running a pure XAML app that doesn't use Win2D at all - the window goes blank, and only recovers when something animates (for instance if you mouse-over in a way that causes a control to change focus).

The combination of these two behaviors introduces an unfortunate race condition.  When the device is resumed, XAML gets a redraw notification (which is then passed on to Win2D).   If the driver TDR happens before we come to process this notification, all is well - we'll try to redraw in response to the notification, notice the error state, and recover the device.  But if we get the notification before the TDR (which can apparently happen in some apps) then we will redraw, and believe all is well, only to have our device be lost out from under us, but at this point we are no longer redrawing anything so don't notice the error until the next time something gets redrawn.

Anyway - that's a long-winded way to say that once the driver is fixed, XAML and Win2D should then work as expected.  Even while the driver bug exists, apps that animate will reliably recover from the error state.  Apps that do not animate will recover at such time as a user interaction causes them to redraw something.

**Comment by shawnhar** [comment] 2017-02-22 20:05
This issue is fixed in the Intel graphics driver version 15.45.10.4550.  Latest drivers are available from https://downloadcenter.intel.com/download/26563/Graphics-Intel-Graphics-Driver-for-Windows-15-45-?v=t

**Closed by shawnhar** 2017-02-22 20:05 UTC
Labels: bug, external
