### ISSUE TITLE
Implement geometry stuff on Geometry class

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/Win2D#132] opened 2015-08-17 22:55 UTC
I want all the stuff available in WPF on Geometry class be available in Windows Runtime

**Comment by shawnhar** [comment] 2015-08-17 22:59
This is a dupe of #130, where I asked you to please file specific bugs for specific requests (for example, in that thread you mentioned ideas like using double vs. float, or ability to stream geometry).

Please create a separate issue for each such topic that you are interested in.  Requests for "all the stuff" are not clearly enough scoped and not clear exactly what you mean by it.

**Closed by shawnhar** 2015-08-17 22:59 UTC
