### ISSUE TITLE
CanvasTextFormat.GetSystemFontFamilies() returns Fonts that cause apps to crash

### ISSUE THREAD

**Issue by mscherotter** [Microsoft/Win2D#409] opened 2016-08-15 21:40 UTC
If a user installs fonts from Adobe Creative Cloud Fonts, they are listed in the CanvasTextFormat.GetSystemFontFamilies() list.  If the fonts are used in a UWP app then the UWP app crashes.
`<TextBlock Text="Tekton Pro Test" FontFamily="Tekton Pro"/>`
CanvasTextFormat.GetSystemFontFamilies() should only return fonts that can be rendered in UWP apps without crashing.
Repro steps:
1. Install an Adobe Creative Cloud Font 
2. Run the Win2D Gallery App
3. Navigate to the TextLayout demo
4. In the Hamburger menu, select the Font combo and scroll to the font that was installed - CRASH!

**Comment by clandrew** [comment] 2016-08-16 00:33
Hi, thanks for sending along this report! GetSystemFontFamilies should be returning usable fonts, so it seems possible that there's a real bug here.
I'll take a look at this.

**Comment by shawnhar** [comment] 2016-08-19 15:21
The root cause of this is broader than just Win2D, as any use of that font causes issues with other apps too (eg. XAML).  The DWrite team is investigating.

For my reference, this is tracked by internal bug #8512526.

**Comment by shawnhar** [comment] 2016-09-06 14:54
Update: this issue is understood, and it will be fixed in the next version of Windows.

**Comment by shawnhar** [comment] 2016-10-31 13:01
This fix is available in the most recent update to Windows 10.

**Closed by shawnhar** 2016-10-31 13:01 UTC
Labels: bug, external
